In [1]:
import pandas as pd
import psycopg2

SAS파일 읽기

In [ ]:
# sas파일을 pandas로 읽음
pd_sas = pd.read_sas('data/hn20_all.sas7bdat', format='sas7bdat')
pd_sas.iloc[:10]

In [10]:
pd_sas

,mod_d,ID,ID_fam,year,region,town_t,apt_t,psu,sex,age,...,LF_S10,LF_S11,LF_S12,LF_S13,LF_S14,LF_S14_1,LF_S15,LF_S16,LF_SECUR,LF_SECUR_G
0,b'2022.02.28.',b'A801169401',b'A8011694',2020.0,1.0,1.0,2.0,b'A801',1.0,39.0,...,3.0,3.0,3.0,8.0,8.0,8.0,8.0,8.0,0.0,1.0
1,b'2022.02.28.',b'A801169402',b'A8011694',2020.0,1.0,1.0,2.0,b'A801',2.0,39.0,...,3.0,3.0,3.0,8.0,8.0,8.0,8.0,8.0,0.0,1.0
2,b'2022.02.28.',b'A801169403',b'A8011694',2020.0,1.0,1.0,2.0,b'A801',1.0,10.0,...,3.0,3.0,3.0,8.0,8.0,8.0,8.0,8.0,0.0,1.0
3,b'2022.02.28.',b'A801169404',b'A8011694',2020.0,1.0,1.0,2.0,b'A801',1.0,7.0,...,3.0,3.0,3.0,8.0,8.0,8.0,8.0,8.0,0.0,1.0
4,b'2022.02.28.',b'A801169405',b'A8011694',2020.0,1.0,1.0,2.0,b'A801',1.0,4.0,...,3.0,3.0,3.0,8.0,8.0,8.0,8.0,8.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7354,b'2022.02.28.',b'R804366601',b'R8043666',2020.0,8.0,1.0,2.0,b'R804',2.0,61.0,...,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,0.0,1.0
7355,b'2022.02.28.',b'R804368301',b'R8043683',2020.0,8.0,1.0,2.0,b'R804',2.0,51.0,...,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,0.0,1.0
7356,b'2022.02.28.',b'R804368302',b'R8043683',2020.0,8.0,1.0,2.0,b'R804',2.0,24.0,...,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,0.0,1.0
7357,b'2022.02.28.',b'R804371701',b'R8043717',2020.0,8.0,1.0,2.0,b'R804',1.0,65.0,...,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,0.0,1.0
7358,b'2022.02.28.',b'R804371702',b'R8043717',2020.0,8.0,1.0,2.0,b'R804',2.0,57.0,...,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,0.0,1.0

In [4]:
# pd_sas (데이터프레임)을 csv 형태로 저장
pd_sas.to_csv('data/pd_sas.csv', index = False, encoding = 'utf-8', sep=',')

pd_sas table 만들기 (pd_sas2 테이블 아님)

In [22]:
# pd_sas 테이블 정의를 위해 컬럼명 List 추출
pd_sas_columns=pd_sas.columns
pd_sas_columns

Index(['mod_d', 'ID', 'ID_fam', 'year', 'region', 'town_t', 'apt_t', 'psu',
       'sex', 'age',
       ...
       'LF_S10', 'LF_S11', 'LF_S12', 'LF_S13', 'LF_S14', 'LF_S14_1', 'LF_S15',
       'LF_S16', 'LF_SECUR', 'LF_SECUR_G'],
      dtype='object', length=752)

In [ ]:
# 테이블 만드는 쿼리문 만들기 (Long)
text_query = 'CREATE TABLE IF NOT EXISTS pd_sas ('
for i in pd_sas_columns:
    text_query = text_query + i + ' varchar(50),'
text_query = text_query.rstrip(',') + ');'

text_query

In [8]:
# postgre DB 연결
try:
    conn = psycopg2.connect(host="172.20.62.185",database="pgdb_final4", user="postgres", password="admin",port=5432)
    print('===접속 성공===')
    cur = conn.cursor()
except psycopg2.DatabaseError as db_err:
    print('접속 오류 !!')
    print(db_err)

===접속 성공===

In [30]:
# pd_sas 테이블 CREATE
cur = conn.cursor()
try:
    cur.execute(text_query)
    conn.commit()
    print('success')
except:
    print('fail')

success

pd_sas2 테이블 만들기 (데이터 입력되는데 인코딩이 다른 듯)

In [ ]:


# #!pip install sqlalchemy
# from sqlalchemy import create_engine
# engine = create_engine('postgresql://postgres:admin@172.20.62.49:5432/pgdb_final4')

# pd_sas.to_sql("pd_sas2", engine)

In [ ]:
# pd_sas2 테이블에 있는 데이터 select 해서 pd_sas2라는 변수에 DF로 저장
cur = conn.cursor()
try:
    cur.execute('select * from pd_sas2')
    pd_sas2 = cur.fetchall()
    conn.commit()
    print('succss')
except:
    conn.rollback()
    print('fail')

In [13]:
len(pd_sas2)

7359

In [17]:
type(pd_sas2)

list

In [19]:
pd.DataFrame(pd_sas2)

,0,1,2,3,4,5,6,7,8,9,...,742,743,744,745,746,747,748,749,750,751
0,b'2022.02.28.',b'N802325804',b'N8023258',2020.0,15.0,1.0,2.0,b'N802',1.0,23.0,...,3.0,3.0,3.0,8.0,8.0,8.0,8.0,8.0,0.0,1.0
1,b'2022.02.28.',b'N802325805',b'N8023258',2020.0,15.0,1.0,2.0,b'N802',1.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,b'2022.02.28.',b'O805349604',b'O8053496',2020.0,16.0,1.0,1.0,b'O805',1.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,b'2022.02.28.',b'N802327501',b'N8023275',2020.0,15.0,1.0,2.0,b'N802',1.0,24.0,...,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,0.0,1.0
4,b'2022.02.28.',b'N802332601',b'N8023326',2020.0,15.0,1.0,2.0,b'N802',2.0,54.0,...,8.0,8.0,8.0,8.0,8.0,8.0,8.0,8.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7354,b'2022.02.28.',b'N802324101',b'N8023241',2020.0,15.0,1.0,2.0,b'N802',1.0,32.0,...,3.0,3.0,3.0,8.0,8.0,8.0,8.0,8.0,0.0,1.0
7355,b'2022.02.28.',b'N802324102',b'N8023241',2020.0,15.0,1.0,2.0,b'N802',2.0,31.0,...,3.0,3.0,3.0,8.0,8.0,8.0,8.0,8.0,0.0,1.0
7356,b'2022.02.28.',b'N802324103',b'N8023241',2020.0,15.0,1.0,2.0,b'N802',1.0,7.0,...,3.0,3.0,3.0,8.0,8.0,8.0,8.0,8.0,0.0,1.0
7357,b'2022.02.28.',b'N802325801',b'N8023258',2020.0,15.0,1.0,2.0,b'N802',1.0,50.0,...,3.0,3.0,3.0,8.0,8.0,8.0,8.0,8.0,0.0,1.0
7358,b'2022.02.28.',b'N802325802',b'N8023258',2020.0,15.0,1.0,2.0,b'N802',2.0,49.0,...,3.0,3.0,3.0,8.0,8.0,8.0,8.0,8.0,0.0,1.0