In [3]:
import pandas as pd
import numpy as np

In [4]:
age18_1 = pd.read_csv('data/age18_1.csv', index_col = 0)
age18_1

C:\Users\USER\AppData\Local\Temp\ipykernel_23392\1173474279.py:1: DtypeWarning: Columns (44,127,291,312,328,409,528,543) have mixed types. Specify dtype option on import or set low_memory=False.
  age18_1 = pd.read_csv('data/age18_1.csv', index_col = 0)

,mod_d,id,ID_fam,year,region,town_t,apt_t,psu,sex,age,...,HEI_TVEG,HEI_VEG,HEI_PROTF,HEI_DAIRY,HEI_SFA,HEI_NA,HEI_SWEET,HEI_CHO,HEI_FAT,HEI_EN
0,b'2022.03.08',b'A701020501',b'A7010205',2018.0,1.0,1.0,2.0,b'A701',1.0,80.0,...,1.367163,0.775022,5.800000,0.000000,5.273475,10.000000,10.00000,5.000000,5.000000,0.000000
1,b'2022.03.08',b'A701021301',b'A7010213',2018.0,1.0,1.0,2.0,b'A701',1.0,78.0,...,4.881043,1.641812,10.000000,10.000000,10.000000,3.418798,10.00000,4.345249,2.956568,5.000000
2,b'2022.03.08',b'A701021302',b'A7010213',2018.0,1.0,1.0,2.0,b'A701',2.0,75.0,...,3.367648,4.943629,4.849725,10.000000,0.000000,9.806158,10.00000,5.000000,5.000000,5.000000
4,b'2022.03.08',b'A701023303',b'A7010233',2018.0,1.0,1.0,2.0,b'A701',2.0,80.0,...,4.619405,0.437024,1.951565,0.000000,10.000000,8.029505,10.00000,0.000000,0.000000,1.244134
5,b'2022.03.08',b'A701023304',b'A7010233',2018.0,1.0,1.0,2.0,b'A701',2.0,71.0,...,2.459564,3.503124,2.135875,10.000000,0.000000,10.000000,10.00000,3.477269,5.000000,5.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7917,b'2022.03.08',b'R707025101',b'R7070251',2018.0,8.0,2.0,1.0,b'R707',1.0,80.0,...,4.416187,2.885425,10.000000,10.000000,0.000000,8.998990,10.00000,5.000000,5.000000,5.000000
7918,b'2022.03.08',b'R707025102',b'R7070251',2018.0,8.0,2.0,1.0,b'R707',2.0,78.0,...,5.000000,5.000000,10.000000,10.000000,4.507390,8.732486,10.00000,5.000000,5.000000,5.000000
7927,b'2022.03.08',b'R707031101',b'R7070311',2018.0,8.0,2.0,1.0,b'R707',2.0,72.0,...,4.272867,2.311358,8.429599,0.000000,10.000000,8.892053,10.00000,4.095630,4.206483,0.000000
7983,b'2022.03.08',b'R708028503',b'R7080285',2018.0,8.0,1.0,2.0,b'R708',2.0,66.0,...,3.398006,3.656502,10.000000,0.023505,10.000000,10.000000,10.00000,5.000000,5.000000,0.000000
7987,b'2022.03.08',b'R708028902',b'R7080289',2018.0,8.0,1.0,2.0,b'R708',2.0,73.0,...,5.000000,3.460232,2.940008,7.280000,6.332807,10.000000,7.98486,2.797653,5.000000,0.000000

# 어떤 변수들이 있을까? (원시자료 지침서 기준)

## 1. 기본변수

1. 기본 변수 (17개)  
mod_d / ID / ID_fam / year / region  
town_t / apt_t / psu / sex / age  
age_month / incm / ho_incm / incm5 / ho_incm5  
edu / occp  

- 가중치 (27개)  
wt_hs / wt_itvex / wt_pft / wt_hm / wt_vt  
wt_nn / wt_exl / wt_ntr / wt_tot / wt_pfhm  
wt_pfhm / wt_pfnt / wt_hmnt / wt_vtnt / wt_nnnt  
wt_pfhmnt / wt_pfvtnt / wt_exlnt / wt_exlhm / wt_exlpf  
wt_wt_totl / wt_exlpfnt / wt_exlhmnt / wt_totlnt / wt_oe  
wt_oent / wt_kstrata  

``` 수정 할 변수 없음 ```

In [227]:
# 1. 기본변수 (전부 이상한 값 없음)
## 1.1. 기본변수 17개
variable_1 = ['mod_d', 'id', 'ID', 'ID_fam', 'year', 'region', \
    'town_t', 'apt_t', 'psu', 'sex', 'age' , \
    'age_month', 'incm', 'ho_incm', 'incm5', 'ho_incm5', \
    'edu', 'occp']
print('variable_1   의 갯수 : {} '.format(len(variable_1)))

## 1.2. 가중치 27개
variable_1wt = ['wt_hs', 'wt_itvex', 'wt_pft', 'wt_hm', 'wt_vt', \
    'wt_nn', 'wt_ex1', 'wt_ntr', 'wt_tot', 'wt_pfhm', \
    'wt_pfvt', 'wt_pfnt', 'wt_hmnt', 'wt_vtnt', 'wt_nnnt', \
    'wt_pfhmnt', 'wt_pfvtnt', 'wt_ex1nt', 'wt_ex1hm', 'wt_ex1pf', \
    'wt_tot1', 'wt_ex1pfnt', 'wt_ex1hmnt', 'wt_tot1nt', 'wt_oe', \
    'wt_oent', 'kstrata', 'wt_ige', 'wt_igent']
print('variable_1wt 의 갯수 : ' + str(len(variable_1wt)))

variable_1   의 갯수 : 18
variable_1wt 의 갯수 : 29

## 2. 건강설문조사

In [249]:
# 2. 건강 설문 조사
## 2.1. 가구조사 + 2.2. 이환
'''
이환
DI1 : 고혈압 / DI2 : 이상지질혈증 / DI3 : 뇌졸중
4 : 심근경색증 또는 협심증 / 5 : 심근경색증 / 6 : 협심증

DM1 : 관절염 / 2 : 골관절염 / 3 : 류마티스성 관절염 / 4 : 골다공증 / 8 : 통풍(8차)
DJ2 : 폐결핵 / 4 : 천식
DE1 : 당뇨병 / 2 : 갑상선 질환
DC1 : 위암 / 2 : 간암 // 3 : 대장암 / 4 : 유방암 / 5 : 자궁경부암 / 6 : 폐암 / 7 : 갑상선암 / 11 : 기타1 / 12 : 기타2
DF2 : 우울증
DL1 : 아토피피부염
DJ8 : 알레르기비염 / 6 : 부비동염
DH4 : 중이염 / 2 : 백내장 / 3 : 녹내장 / 6 : 황반변성
DN1 : 신부전
DK8 : B형간염 / 9 : C형간염 / 4 : 간경변증
BP17 : 폐쇄성수면무호흡증
'''
### 제거 할 값이 없는 컬럼
variable_21 = ['ID_F', 'ID_M', 'id_f', 'id_F', 'id_m', 'id_M', 'DE1_35', 'DC11_tp', 'DC12_tp']
print('variable_21   의 갯수 : ' + str(len(variable_21)))

### 8, 9 제거 할 컬럼
variable_21_1 = ['cfam', 'genertn', 'house' ,'live_t', 'ainc_unit1', \
    'marri_1', 'marri_2', 'npins', 'D_1_1', 'D_2_1', \
    'DI1_dg', 'DI1_pr', 'DI1_pt', 'DI1_2', \
    'DI2_dg', 'DI2_pr', 'DI2_pt', 'DI2_2', \
    'DI3_dg', 'DI3_pr', 'DI3_pt', 'DI3_2', \
    'DI4_dg', 'DI4_pr', 'DI4_pt', \
    'DI5_dg', 'DI5_pr', 'DI5_pt', \
    'DI6_dg', 'DI6_pr', 'DI6_pt', \
    'DM1_dg', 'DM1_pr', 'DM1_pt', \
    'DM2_dg', 'DM2_pr', 'DM2_pt', \
    'DM3_dg', 'DM3_pr', 'DM3_pt', \
    'DM4_dg', 'DM4_pr', 'DM4_pt', \
    'DJ2_dg', 'DJ2_pr', 'DJ2_pt', \
    'DJ4_dg', 'DJ4_pr', 'DJ4_pt', 'DJ4_3', 'DJ6_dg', 'DJ6_pr', 'DJ6_pt', \
    'DE1_dg', 'DE1_pr', 'DE1_pt', 'DE1_3', 'DE1_31', 'DE1_32', 'DE1_33', 'DE1_34', 'DE1_4', \
    'DE2_dg', 'DE2_pr', 'DE2_pt', \
    'DC1_dg', 'DC1_pr', 'DC1_pt', \
    'DC2_dg', 'DC2_pr', 'DC2_pt', \
    'DC3_dg', 'DC3_pr', 'DC3_pt', \
    'DC4_dg', 'DC4_pr', 'DC4_pt', \
    'DC5_dg', 'DC5_pr', 'DC5_pt', \
    'DC6_dg', 'DC6_pr', 'DC6_pt', \
    'DC7_dg', 'DC7_pr', 'DC7_pt', \
    'DC11_dg', 'DC11_pr', 'DC11_pt', \
    'DC12_dg', 'DC12_pr', 'DC12_pt', \
    'DF2_dg', 'DF2_pr', 'DF2_pt', \
    'DL1_dg', 'DL1_pr', 'DL1_pt', \
    'DJ8_dg', 'DJ8_pr', 'DJ8_pt', \
    'DH4_dg', 'DH4_pr', 'DH4_pt', \
    'DH2_dg', 'DH2_pr', 'DH2_pt', \
    'DH3_dg', 'DH3_pr', 'DH3_pt', \
    'DH6_dg', 'DH6_pr', 'DH6_pt', \
    'DN1_dg', 'DN1_pr', 'DN1_pt', \
    'DK8_dg', 'DK8_pr', 'DK8_pt', \
    'DK9_dg', 'DK9_pr', 'DK9_pt', \
    'DK4_dg', 'DK4_pr', 'DK4_pt', \
    'DM8_dg', 'DM8_pr', 'DM8_pt', \
    'BP17_dg']
print('variable_21_1 의 갯수 : ' + str(len(variable_21_1)))

### 88, 99 제거 할 컬럼
variable_21_2 = ['allownc', 'marri_2', 'fam_rela', 'tins', 'D_2_wk']
print('variable_21_2 의 갯수 : ' + str(len(variable_21_2)))

### 888, 999 제거 할 컬럼
variable_21_3 = ['DI1_ag', 'DI2_ag', 'DI3_ag', 'DI5_ag', 'DI6_ag', \
    'DM2_ag', 'DM3_ag', 'DM4_ag', \
    'DJ2_ag',           'DJ4_ag', \
    'DE1_ag', 'DE2_ag', \
    'DC1_ag', 'DC2_ag', 'DC3_ag', 'DC4_ag', 'DC5_ag', 'DC6_ag', 'DC7_ag', 'DC11_ag', 'DC12_ag', \
    'DF2_ag', 'DL1_ag', 'DJ8_ag', 'DJ6_ag', \
    'DH4_ag', 'DH2_ag', 'DH3_ag', 'DH6_ag', \
    'DN1_ag', 'DK8_ag', 'DK9_ag', 'DK4_ag', \
    'DM8_ag']
print('variable_21_3 의 갯수 : ' + str(len(variable_21_3)))

### 999999 제거 할 컬럼
variable_21_6 = ['ainc_1', 'ainc']
print('variable_21_6 의 갯수 : ' + str(len(variable_21_6)))

variable_21   의 갯수 : 9
variable_21_1 의 갯수 : 129
variable_21_2 의 갯수 : 5
variable_21_3 의 갯수 : 34
variable_21_6 의 갯수 : 2

In [53]:
# 의미 없는 컬럼
'''
소아청소년 질환 (young29 = 8개)
'''
young21 =  ['DI9_yd', 'DI9_ya', 'DF1_yd', 'DF1_ya', 'DN6_yd', 'DN6_ya', 'DJ9_yd', 'DJ9_ya']
print('young21 의 갯수 : ' + str(len(young21)))

young21 의 갯수 : 8

In [228]:
# 2-3. 의료이용 + 2-4. 건강검진 및 예방접종 + 2-5. 활동제한 및 삶의 질
### 제거 할 값이 없는 컬럼
variable_23 = ['M_2_et', 'mt_nontrt', 'BH9_14_4_01', 'BH9_14_4_02', 'BH9_14_4_03', 'BH1_7', 'BH2_65', 'LQ4_24', 'EQ5D']
print('variable_23   의 갯수 : ' + str(len(variable_23)))

### 8, 9 제거 할 컬럼
variable_23_1 = ['M_2_yr', 'BH9_11', 'BH9_14_3_01', 'BH9_14_3_02', 'BH9_14_3_03', \
    'BH1', 'BH1_1', 'BH1_2', 'BH1_3', 'BH1_8', 'BH1_6', \
    'BH2_61', 'BH2_62', 'BH2_63', 'BH2_66', 'BH2_67', 'BH2_64', \
    'LQ4_00', 'LQ4_01', 'LQ4_02', 'LQ4_03', 'LQ4_04', \
    'LQ4_05', 'LQ4_06', 'LQ4_07', 'LQ4_08', 'LQ4_09', \
    'LQ4_10', 'LQ4_11', 'LQ4_12', 'LQ4_13', 'LQ4_14', \
    'LQ4_15', 'LQ4_16', 'LQ4_21', 'LQ4_22', 'LQ4_25', \
    'LQ4_26', 'LQ4_27', 'LQ4_28', 'LQ4_29', 'LQ4_23', \
    'LQ4_17', 'LQ4_18', 'LQ4_19', 'LQ4_20', \
    'LQ1_sb', 'LQ3_sb', 'LQ2_ab', 'LQ4_ab', \
    'LQ_1EQL', 'LQ_2EQL', 'LQ_3EQL', 'LQ_4EQL', 'LQ_5EQL', \
    'LQ_1HT', 'LQ_2HT', 'LQ_3HT', 'LQ_4HT', 'LQ_5HT', 'LQ_6HT', 'LQ_7HT', 'LQ_8HT']
print('variable_23_1 의 갯수 : ' + str(len(variable_23_1)))

### 88, 99 제거 할 컬럼
variable_23_2 = ['M_2_rs', 'BH9_13', 'BH9_14_2_01', 'BH9_14_2_02', 'BH9_14_2_03', \
    'LQ1_mn', 'LQ2_mn']
print('variable_23_2 의 갯수 : ' + str(len(variable_23_2)))

### 888, 999 제거 할 컬럼
variable_23_3 = ['LQ3_mn', 'LQ4_mn']
print('variable_23_3 의 갯수 : ' + str(len(variable_23_3)))

### 9999 제거 할 컬럼
variable_23_4 = ['BH9_14_1_01', 'BH9_14_1_02', 'BH9_14_1_03']
print('variable_23_4 의 갯수 : ' + str(len(variable_23_4)))

variable_23   의 갯수 : 9
variable_23_1 의 갯수 : 63
variable_23_2 의 갯수 : 7
variable_23_3 의 갯수 : 2
variable_23_4 의 갯수 : 3

In [51]:
# 2-6. 손상(사고 및 중독) + 2-7. 입원이용 + 2-8. 외래이용
### 제거 할 값이 없는 컬럼
variable_26 = ['AC3_3e_01', 'AC3_3e_02', 'AC3_3e_03', 'AC3_3e_04', 'AC3_3e_05', \
    'AC3_3e_06', 'AC3_3e_07', 'AC3_3e_08', 'AC3_3e_09', 'AC3_3e_10', \
    'AC8_1e_01', 'AC8_1e_02', 'AC8_1e_03', 'AC8_1e_04', 'AC8_1e_05', \
    'AC8_1e_06', 'AC8_1e_07', 'AC8_1e_08', 'AC8_1e_09', 'AC8_1e_10', \
    'ij_expr']
print('variable_26   의 갯수 : ' + str(len(variable_26)))

### 8, 9 제거 할 컬럼
variable_26_1 = ['AC1_yr', 'AC3_3_01', 'AC3_3_02', 'AC3_3_03', 'AC3_3_04', 'AC3_3_05', \
    'AC3_3_06', 'AC3_3_07', 'AC3_3_08', 'AC3_3_09', 'AC3_3_10', \
    'AC8_1_01', 'AC8_1_02', 'AC8_1_03', 'AC8_1_04', 'AC8_1_05', \
    'AC8_1_06', 'AC8_1_07', 'AC8_1_08', 'AC8_1_09', 'AC8_1_10', \
    'AC3_4_01', 'AC3_4_02', 'AC3_4_03', 'AC3_4_04', 'AC3_4_05', \
    'AC3_4_06', 'AC3_4_07', 'AC3_4_08', 'AC3_4_09', 'AC3_4_10', \
    'AC8_2w_01', 'AC8_2w_02', 'AC8_2w_03', 'AC8_2w_04', 'AC8_2w_05', \
    'AC8_2w_06', 'AC8_2w_07', 'AC8_2w_08', 'AC8_2w_09', 'AC8_2w_10', \
    'AC8_3w_01', 'AC8_3w_02', 'AC8_3w_03', 'AC8_3w_04', 'AC8_3w_05', \
    'AC8_3w_06', 'AC8_3w_07', 'AC8_3w_08', 'AC8_3w_09', 'AC8_3w_10', \
    'MH1_yr', 'MO1_wk']
print('variable_26_1 의 갯수 : ' + str(len(variable_26_1)))

### 88, 99 제거 할 컬럼
variable_26_2 = ['AC3', 'AC3_2_01', 'AC3_2_02', 'AC3_2_03', 'AC3_2_04', 'AC3_2_05', \
    'AC3_2_06', 'AC3_2_07', 'AC3_2_08', 'AC3_2_09', 'AC3_2_10', \
    'MH1_1', 'MO1_1']
print('variable_26_2 의 갯수 : ' + str(len(variable_26_2)))

### 888, 999 제거 할 컬럼
variable_26_3 = ['AC8_2_01', 'AC8_2_02', 'AC8_2_03', 'AC8_2_04', 'AC8_2_05', \
    'AC8_2_06', 'AC8_2_07', 'AC8_2_08', 'AC8_2_09', 'AC8_2_10', \
    'AC8_3_01', 'AC8_3_02', 'AC8_3_03', 'AC8_3_04', 'AC8_3_05', \
    'AC8_3_06', 'AC8_3_07', 'AC8_3_08', 'AC8_3_09', 'AC8_3_10']
print('variable_26_3 의 갯수 : ' + str(len(variable_26_3)))

### 9999 제거 할 컬럼
variable_26_4 = ['AC3_1_01', 'AC3_1_02', 'AC3_1_03', 'AC3_1_04', 'AC3_1_05', \
    'AC3_1_06', 'AC3_1_07', 'AC3_1_08', 'AC3_1_09', 'AC3_1_10']
print('variable_26_4 의 갯수 : ' + str(len(variable_26_4)))

variable_26   의 갯수 : 21
variable_26_1 의 갯수 : 53
variable_26_2 의 갯수 : 13
variable_26_3 의 갯수 : 20
variable_26_4 의 갯수 : 10

In [56]:
# 2-9. 교육 및 경제 활동
### 제거 할 값이 없는 컬럼
variable_29 = ['EC1_2_1', 'EC_wht_6']
print('variable_29   의 갯수 : ' + str(len(variable_29)))

### 8, 9 제거 할 컬럼
variable_29_1 = ['graduat', 'EC1_1', 'EC1_2', 'EC_stt_1', 'EC_stt_2', 'EC_wh', 'EC_wht_0', 'EC_lgw_4', 'EC_lgw_5']
print('variable_29_1 의 갯수 : ' + str(len(variable_29_1)))

### 88, 99 제거 할 컬럼
variable_29_2 = ['educ', 'EC_occp', 'EC_wht_5', 'EC_lgw_2', 'EC_pedu_1', 'EC_pedu_2']
print('variable_29_2 의 갯수 : ' + str(len(variable_29_2)))

### 888, 999 제거 할 컬럼
variable_29_3 = ['EC_wht_23']
print('variable_29_3 의 갯수 : ' + str(len(variable_29_3)))

variable_29   의 갯수 : 2
variable_29_1 의 갯수 : 9
variable_29_2 의 갯수 : 6
variable_29_3 의 갯수 : 1
variable_29_4 의 갯수 : 0

In [66]:
# 의미 없는 컬럼
'''
청소년 및 소아 질문
'''
young29 =  ['h_school_t', 'h_school_t_1', 'CH2_1', 'CH2_1', 'CH2_2']
print('young29 의 갯수 : ' + str(len(young29)))

young29 의 갯수 : 5

In [229]:
# 2-10. 비만 및 체중조절 + 2-11. 음주
### 제거 할 값이 없는 컬럼
variable_210 = ['BO3_03', 'BO3_11', 'BD2_14', 'BD7_67', 'dr_month']
print('variable_210   의 갯수 : ' + str(len(variable_210)))

### 8, 9 제거 할 컬럼
variable_210_1 = ['BO1', 'BO1_1', 'BO1_2', 'BO1_3', 'BO2_1', 'BO3_01', 'BO3_02', 'BO3_14', \
    'BO3_05', 'BO3_04', 'BO3_12', 'BO3_07', 'BO3_09', 'BO3_10', \
    'BD1', 'BD1_11', 'BD2_1', 'BD2_31', 'BD2_32', \
    'BD7_4', 'BD7_5', 'BD7_6', 'BD7_61', 'BD7_62', 'BD7_63', \
    'BD7_64', 'BD7_65', 'BD7_66', \
    'BD9_1', 'BD9_2']
print('variable_210_1 의 갯수 : ' + str(len(variable_210_1)))

### 888, 999 제거 할 컬럼
variable_210_3 = ['BD2']
print('variable_210_3 의 갯수 : ' + str(len(variable_210_3)))

variable_210   의 갯수 : 5
variable_210_1 의 갯수 : 30
variable_210_3 의 갯수 : 1

In [230]:
# 2-12. 안전의식 + 2-13. 정신건강
### 제거 할 값이 없는 컬럼
variable_212 = ['sc_seatblt', 'sc_seatblt2', 'mh_PHQ_S', 'BP2_2', 'mh_stress', 'sc_seatblt3']
print('variable_212   의 갯수 : ' + str(len(variable_212)))

### 8, 9 제거 할 컬럼
variable_212_1 = ['BA2_12', 'BA2_13', 'BA2_14', 'BA1_3', 'BA1_5', 'BA2_2_1', 'BA2_2_3', \
    'BA2_2_5', 'BA2_22', 'BA1_1', 'BA1_2', \
    'BP_PHQ_1', 'BP_PHQ_2', 'BP_PHQ_3', 'BP_PHQ_4', 'BP_PHQ_5', \
    'BP_PHQ_6', 'BP_PHQ_7', 'BP_PHQ_8', 'BP_PHQ_9', \
    'BP1', 'BP5', 'BP6_10', 'BP6_2', 'BP6_31', 'BP7', \
    'BP17_2', 'BP17_3', 'BP17_4']
print('variable_212_1 의 갯수 : ' + str(len(variable_212_1)))

### 88, 99 제거 할 컬럼
variable_212_2 = ['BP16_11', 'BP16_12', 'BP16_13', 'BP16_14', \
    'BP16_21', 'BP16_22', 'BP16_23', 'BP16_24', \
    'BP2', 'BP16_1', 'BP16_2']
print('variable_212_2 의 갯수 : ' + str(len(variable_212_2)))

### 888, 999 제거 할 컬럼
variable_212_3 = ['BA2_2_2', 'BA2_2_4', \
    'BA2_2_6']
print('variable_212_3 의 갯수 : ' + str(len(variable_212_3)))

### 9999 제거 할 컬럼
variable_212_4 = ['Total_slp_wk', 'Total_slp_wd']
print('variable_212_4 의 갯수 : ' + str(len(variable_212_4)))

variable_212   의 갯수 : 6
variable_212_1 의 갯수 : 29
variable_212_2 의 갯수 : 11
variable_212_3 의 갯수 : 3
variable_212_4 의 갯수 : 2

In [250]:
# 2-14. 흡연
### 제거 할 값이 없는 컬럼
variable_214 = ['BS5_31', 'BS12_22', 'BS12_35', 'BS12_45', 'sm_presnt', 'BS12_47_5']
print('variable_214   의 갯수 : ' + str(len(variable_214)))

### 8, 9 제거 할 컬럼
variable_214_1 = ['BS1_1', 'BS3_1', 'BS5_4', 'BS5', \
    'BS5_1', 'BS5_5', 'BS5_21', 'BS5_28', 'BS5_26', \
    'BS5_33', 'BS5_34', 'BS5_32', 'BS5_29', 'BS5_30', \
    'BS8_2', 'BS9_2', 'BS13', 'BS11', \
    'BS12_1', 'BS12_2', \
    'BS12_31', 'BS12_32', 'BS12_33', 'BS12_37', 'BS12_34', 'BS12_36', \
    'BS12_41', 'BS12_42', 'BS12_43', 'BS12_47', 'BS12_44', 'BS12_46', \
    ]
print('variable_214_1 의 갯수 : ' + str(len(variable_214_1)))

### 88, 99 제거 할 컬럼
variable_214_2 = ['BS3_3', 'BS6_2_1', 'BS6_2_2', 'BS6_4_1', 'BS6_4_2', \
    'BS12_21', 'BS12_47_2', 'BS12_47_4']
print('variable_214_2 의 갯수 : ' + str(len(variable_214_2)))

### 888, 999 제거 할 컬럼
variable_214_3 = ['BS2_1', 'BS2_2', 'BS3_2', 'BS6_3', 'BS12_47_1']
print('variable_214_3 의 갯수 : ' + str(len(variable_214_3)))

### 9999 제거 할 컬럼
variable_214_4 = ['BS6_2', 'BS6_4']
print('variable_214_4 의 갯수 : ' + str(len(variable_214_4)))

variable_214   의 갯수 : 6
variable_214_1 의 갯수 : 32
variable_214_2 의 갯수 : 8
variable_214_3 의 갯수 : 5
variable_214_4 의 갯수 : 2

In [65]:
# 의미 없는 컬럼
'''
청소년 및 소아 질문
'''
young214 =  ['BS10_1', 'BS2', 'BS10_2', 'BS10_3']
print('young214 의 갯수 : ' + str(len(young214)))

young214 의 갯수 : 4

In [70]:
# 2-15. 신체활동
### 제거 할 값이 없는 컬럼
variable_215 = ['pa_aerobic']
print('variable_215   의 갯수 : ' + str(len(variable_215)))

### 8, 9 제거 할 컬럼
variable_215_1 = ['BE3_71', 'BE3_72', 'BE3_81', 'BE3_82', 'BE3_91', 'BE3_92', \
    'BE3_75', 'BE3_76', 'BE3_85', 'BE3_86', 'BE5_1', 'BE9']
print('variable_215_1 의 갯수 : ' + str(len(variable_215_1)))

### 88, 99 제거 할 컬럼
variable_215_2 = ['BE3_73', 'BE3_74', 'BE3_83', 'BE3_84', 'BE3_93', 'BE3_94', \
    'BE3_77', 'BE3_78', 'BE3_87', 'BE3_88', 'BE8_1', 'BE8_2', 'BE3_31', \
    'BE3_32', 'BE3_33']
print('variable_215_2 의 갯수 : ' + str(len(variable_215_2)))

variable_215   의 갯수 : 1
variable_215_1 의 갯수 : 12
variable_215_2 의 갯수 : 15
variable_215_3 의 갯수 : 0
variable_215_4 의 갯수 : 0

In [72]:
# 2-16. 여성건강
### 제거 할 값이 없는 컬럼
variable_216 = ['LW_mp_e']
print('variable_216   의 갯수 : ' + str(len(variable_216)))

### 8, 9 제거 할 컬럼
variable_216_1 = ['LW_ms', 'LW_pr', 'LW_mt', 'LW_br', 'LW_oc']
print('variable_216_1 의 갯수 : ' + str(len(variable_216_1)))

### 88, 99 제거 할 컬럼
variable_216_2 = ['LW_pr_1', 'LW_br_ch', 'LW_br_yy', 'LW_br_mm']
print('variable_216_2 의 갯수 : ' + str(len(variable_216_2)))

### 888, 999 제거 할 컬럼
variable_216_3 = ['LW_mp_a', 'LW_ms_a', 'LW_mt_a1', 'LW_mt_a2']
print('variable_216_3 의 갯수 : ' + str(len(variable_216_3)))

### 9999 제거 할 컬럼
variable_216_4 = ['LW_br_dur']
print('variable_216_4 의 갯수 : ' + str(len(variable_216_4)))

variable_216   의 갯수 : 1
variable_216_1 의 갯수 : 5
variable_216_2 의 갯수 : 4
variable_216_3 의 갯수 : 4
variable_216_4 의 갯수 : 1

## 3. 검진조사

In [259]:
# 3. 검진조사
# 3-1. 검진 기본조사 + 3-2. 혈압 측정 + 3-3. 신체계측 + 3-4. 혈액검사 + 3.5. 소변검사
# 3-6. 폐기능 검사 + 3-7. 구강검사 ( 3-7-2. 치아번호 필요. 컬럼 확인해보고 없으면 그때 하기 7차 194Page )
### 제거 할 값이 없는 컬럼
variable_31 = ['HE_fst', 'HE_HPdg', 'HE_HPdr', 'HE_DMdg', 'HE_DMdr', 'HE_dprg', \
    'HE_rPLS', 'HE_PLS', 'HE_PLS_30', 'HE_mPLS', 'HE_nARM', \
    'HE_sbp1', 'HE_dbp1', 'HE_sbp2', 'HE_dbp2', 'HE_sbp3', 'HE_dbp3', 'HE_sbp', 'HE_dbp', 'HE_HP', \
    'HE_ht', 'HE_wt', 'HE_wc', 'HE_BMI', 'HE_obe', 'HE_wt_pct', 'HE_BMI_pct', \
    'HE_glu', 'HE_HbA1c', 'HE_DM', \
    'HE_chol', 'HE_HDL_st2', 'HE_TG', 'HE_LDL_drct', 'HE_HCHOL', 'HE_HTG', \
    'HE_HBsAg', 'HE_ast', 'HE_alt', 'HE_alt_etc', 'HE_hepaB', 'HE_hcv', 'HE_hepaC', \
    'HE_HB', 'HE_HCT', 'HE_anem', 'HE_BUN', 'HE_crea', \
    'HE_WBC', 'HE_RBC', 'HE_Bplt', 'HE_hsCRP', 'HE_hsCRP_etc', \
    'HE_Uacid', 'HE_Uacid_etc', 'HE_Folate', 'HE_Folate_etc', 'HE_VitA', 'HE_VitE', \
    'HE_Pb', 'HE_Hg', 'HE_Cd', 'HE_Ni', \
    'HE_Uph', 'HE_Unitr', 'HE_Usg', 'HE_Upro', 'HE_Uglu', 'HE_Uket', \
    'HE_Ubil', 'HE_Ubld', 'HE_Uro', 'HE_Ucot', 'HE_Ucot_etc', 'HE_NNAL', \
    'HE_NNAL_etc', 'HE_UCREA', 'HE_UNa', 'HE_Una', \
    'HE_UNa_etc', 'HE_Una_etc', 'HE_Ukal', 'HE_Ukal_etc', 'HE_Nnal', 'HE_Nnal_etc', \
    'HE_fvc', 'HE_fvcp', 'HE_fev1', 'HE_fev1p', 'HE_fev1fvc', 'HE_fev6', 'HE_fef25_75', 'HE_pef', 'HE_COPD', \
    'HE_cough1', 'HE_cough2', 'HE_sput1', 'HE_sput2', 'HE_PFTdr', 'HE_PFTag', 'HE_PFTtr', 'HE_PFThs', \
    'O_DTD', 'O_DTP', 'O_DID', 'O_DIP', 'O_DFTD', 'O_DMFTP', 'O_DFID', 'O_DMFIP', \
    'O_IMP_U', 'O_IMP_L', 'O_BR_N_U', 'O_BR_N_L', 'O_DENT_U', 'O_DENT_L', \
    'NO_CPI_34', 'BM13_6', 'O_chew_d', 'BM14_2', \
    'HE_nc', \
    'HE_nc', 'HE_insulin', 'HE_insulin_etc', 'HE_DM_HbA1c', 'HE_df', \
    'HE_dog', 'HE_cat', 'HE_birch', 'HE_oak', 'HE_Jhop', 'HE_ragweed', \
    'HE_Ucrea', 'HE_Ucrea_etc', 'HE_Ualb', 'HE_Ualb_etc']
print('variable_31   의 갯수 : ' + str(len(variable_31)))

### 8, 9 제거 할 컬럼
variable_31_1 = ['HE_mens', 'HE_prg', \
    'HE_fh', 'HE_HPfh1', 'HE_HPfh2', 'HE_HPfh3', \
    'HE_HLfh1', 'HE_HLfh2', 'HE_HLfh3', \
    'HE_IHDfh1', 'HE_IHDfh2', 'HE_IHDfh3', \
    'HE_STRfh1', 'HE_STRfh2', 'HE_STRfh3', \
    'HE_DMfh1', 'HE_DMfh2', 'HE_DMfh3', \
    'HE_THfh1', 'HE_THfh2', 'HE_THfh3', \
    'HE_HBfh1', 'HE_HBfh2', 'HE_HBfh3', \
    'O_PROS_U', 'O_PROS_L', \
    'O_F', 'O_CPI_UR', 'O_CPI_UM', 'O_CPI_UL', 'O_CPI_LR', 'O_CPI_LM', 'O_CPI_LL', \
    'OR1', 'O_pain', 'O_ortho', \
    'BM1_0', 'BM1_1', 'BM1_2', 'BM1_3', 'BM1_4', 'BM1_5', 'BM1_6', 'BM1_7', 'BM1_8', \
    'BM2_1', 'BM2_3', 'BM2_2', 'BM2_4', 'BM2_5', \
    'BM13', 'BM13_1', 'BM13_2', 'BM13_3', 'BM13_4', 'BM13_5', 'BM7', \
    'BM8', 'OR1_2', 'MO4_00', 'MO4_4', 'MO4_9', 'MO4_7', 'MO4_8', \
    'MO4_17', 'MO4_17_1', 'MO4_17_2', 'MO4_11', 'MO4_12', 'MO4_18', 'MO4_15', \
    'BM14']
print('variable_31_1 의 갯수 : ' + str(len(variable_31_1)))

### 88, 99 제거 할 컬럼
variable_31_2 = ['BM14_1']
print('variable_31_2 의 갯수 : ' + str(len(variable_31_2)))

variable_31   의 갯수 : 136
variable_31_1 의 갯수 : 72
variable_31_2 의 갯수 : 1

In [237]:
# 3-8. 이비인후검사 + 3-9. 안검사 + 3-10. 악력검사
### 제거 할 값이 없는 컬럼
variable_38 = ['T_ex', 'T_EX', 'E_ex', 'E_AMD', 'E_EM', 'E_DM', 'E_GR', \
    'GS_mea_r_1', 'GS_mea_r_2', 'GS_mea_r_3', \
    'GS_mea_l_1', 'GS_mea_l_2', 'GS_mea_l_3', \
    'T_HR_EX_R', 'T_HR_EX_R_1', 'T_HR_EX_R_2', 'T_HR_EX_L', 'T_HR_EX_L_1', 'T_HR_EX_L_2', \
    'T_HR500_pass', 'T_HR1000_pass', 'T_HR2000_pass', 'T_HR4000_pass', \
    'T_HR500_RT', 'T_HR1000_RT', 'T_HR2000_RT', 'T_HR4000_RT', 'T_HR8000_RT', \
    'T_HR500_LT', 'T_HR1000_LT', 'T_HR2000_LT', 'T_HR4000_LT', 'T_HR8000_LT', \
    'T_HL_moderate', 'T_HL_mod', 'T_HL_mild', \
    'T_IM_EX_R', 'T_IM_EX_R_1', 'T_IM_EX_R_2', 'T_IM_EX_L', 'T_IM_EX_L_1', 'T_IM_EX_L_2', \
    'T_IM_A_R', 'T_IM_A_L', 'T_IM_B_R', 'T_IM_B_L', 'T_IM_C_R', 'T_IM_C_L', 'T_IM_FL_R', 'T_IM_FL_L', \
    'T_Tymp_Dis', 'T_balance', \
    ]
print('variable_38   의 갯수 : ' + str(len(variable_38)))

### 8, 9 제거 할 컬럼
variable_38_1 = ['T_Q_HR', 'T_Q_HR1', 'T_Q_VN', 'T_Q_VN1', 'T_NQ_PH', \
    'T_NQ_OCP', 'T_NQ_OCP_P', 'T_NQ_LS', 'T_NQ_FIR', 'T_NQ_FIR_P', \
    'E_Q_EX', 'E_Q_FAM', 'E_DG', 'E_PEO', 'E_DR', 'E_NWT', \
    'E_CO', 'E_CO_1', 'E_PO', 'E_PO_1', \
    'E_Cr_m', 'E_Cl_m', 'E_DO', \
    'GS_use', 'T_Q_HR_1', 'T_Q_HR_2', 'T_Q_VN_1', \
    'T_Q_DZ', 'T_Q_DZ2', 'T_Q_DZ3', 'T_Q_DZ4', 'T_Q_DZ5', 'T_Q_DZ6', \
    'T_Q_DZ7', 'T_Q_CR', 'T_Q_CR1', 'T_Q_CR2', 'T_Q_CR3', 'T_Q_CR4', \
    'T_Q_ALLE', 'T_Q_SNST1', 'T_Q_SNST2', 'T_Q_SNST3', 'T_Q_SNST4', \
    'T_Q_SINU', 'T_Q_SINU_1', 'T_Q_VC', 'T_Q_VC1']
print('variable_38_1 의 갯수 : ' + str(len(variable_38_1)))

### 88, 99 제거 할 컬럼
variable_38_2 = ['E_Cr_1', 'E_Cl_1', 'E_Dr_2_1', 'E_Dr_3_1', 'E_Dl_2_1', 'E_Dl_3_1', \
    'T_Q_VN_2']
print('variable_38_2 의 갯수 : ' + str(len(variable_38_2)))

### 888, 999 제거 할 컬럼
variable_38_3 = ['T_NQ_PH_T', 'T_NQ_OCP_T', 'T_NQ_LS_T', \
    'E_PEO_1', 'E_DR1']
print('variable_38_3 의 갯수 : ' + str(len(variable_38_3)))

### 8888, 9999 제거 할 컬럼
variable_38_4 = ['E_Dr_a', 'E_Dl_a']
print('variable_38_4 의 갯수 : ' + str(len(variable_38_4)))

### 88888, 99999 제거 할 컬럼
variable_38_5 = ['E_Q_FAM1', 'E_DG1']
print('variable_38_5 의 갯수 : ' + str(len(variable_38_5)))

### 888.88 999.99 제거 할 컬럼
variable_38_32 = ['E_Dr_dsph', 'E_Dr_dcyl', 'E_Dl_dsph', 'E_Dl_dcyl']
print('variable_38_32 의 갯수 : ' + str(len(variable_38_32)))

variable_38   의 갯수 : 52
variable_38_1 의 갯수 : 48
variable_38_2 의 갯수 : 7
variable_38_3 의 갯수 : 5
variable_38_4 의 갯수 : 2
variable_38_5 의 갯수 : 2
variable_38_32 의 갯수 : 4

## 4. 영양조사

In [242]:
# 4. 영양조사
# 4-1. 식생활조사 + (4-2.는 다음코드에) + 4-3. 식품섭취조사 (있는컬럼만 확인해서 넣음)
# ### 제거 할 값이 없는 컬럼
variable_41 = ['L_BR', 'L_LN', 'L_DN', 'L_BR_FQ', 'L_LN_FQ', 'L_DN_FQ', \
    'N_DT_DS', 'N_DT_ETC', 'N_DUSUAL', 'N_WAT_C', 'N_DAY', 'N_MEAL', \
    'N_DNAME', 'N_DCODE', 'N_CD_VOL' ,'N_CD_WT' ,'N_TD_VOL' ,'N_TD_WT', \
    'N_FCODE', 'N_FNAME', 'N_ENAME' ,'N_FD_NS' ,'N_FM_WT' ,'N_PRODUCT', \
    'N_CNAME', 'N_AP', 'N_KINDG1' ,'N_KINDG2' ,'N_FCODE3' ,'N_FNAME3', \
    'NF_INTK', 'NF_INTK3']
print('variable_41   의 갯수 : ' + str(len(variable_41)))

### 8, 9 제거 할 컬럼
variable_41_1 = ['L_OUT_FQ', 'L_BR_TO', 'L_BR_WHO', \
    'L_LN_TO', 'L_LN_WHO', 'L_DN_TO', 'L_DN_WHO', \
    'LS_1YR', 'LK_EDU', 'LK_LB_CO', 'LK_LB_US', 'LK_LB_EF', \
    'Y_MTM_YN', 'Y_FM_YN', 'Y_SUP_YN', 'Y_SUP_KD1', 'Y_SUP_KD3', 'Y_SUP_KD4', 'Y_SUP_KD7', \
    'N_DIET', 'N_DIET_WHY', 'N_PRG', 'N_BFD_Y', 'N_MEAL_W'
    ]
print('variable_41_1 의 갯수 : ' + str(len(variable_41_1)))

### 88, 99 제거 할 컬럼
variable_41_2 = ['LK_LB_IT', 'N_MEAL_P', 'N_MTYPE', \
    'DQ_CWATER', 'DA_CWATER', 'DQ_SODA', 'DA_SODA', 'DQ_SPORTS', 'DA_SPORTS', \
    'DQ_CAFFEINE', 'DA_CAFFEINE', 'DQ_FVJUICE', 'DA_FVJUICE', 'DQ_SFVJUICE', 'DA_SFVJUICE', \
    'DQ_COFFEE', 'DA_COFFEE', 'DQ_SCOFFEE', 'DA_SCOFFEE', 'DQ_TEA', 'DA_TEA', \
    'DQ_STEA', 'DA_STEA', 'DQ_MILK', 'DA_MILK', 'DQ_SMILK', 'DA_SMILK', \
    'DQ_YOGURT', 'DA_YOGURT']
print('variable_41_2 의 갯수 : ' + str(len(variable_41_2)))

### 888, 999 제거 할 컬럼
variable_41_3 = ['Y_BTH_WT', 'Y_MTM_S1', 'Y_MTM_S2', 'Y_MTM_D1', 'Y_MTM_D2', \
    'Y_FM_S1', 'Y_FM_S2', 'Y_FM_D1', 'Y_FM_D2', 'Y_MLK_ST', 'Y_WN_ST']
print('variable_41_3 의 갯수 : ' + str(len(variable_41_3)))

### 8881, 8882, 8883 제거 할 컬럼
variable_41_4_3 = ['N_MEAL_T']
print('variable_41_4_3 의 갯수 : ' + str(len(variable_41_4_3)))

### 98, 99 제거
variable_41_2_1 = ['N_MEAL_P']
print('variable_41_2_1 의 갯수 : ' + str(len(variable_41_2_1)))

variable_41   의 갯수 : 32
variable_41_1 의 갯수 : 24
variable_41_2 의 갯수 : 29
variable_41_3 의 갯수 : 11
variable_41_4_3 의 갯수 : 1
variable_41_2_1 의 갯수 : 1

In [239]:
# 의미 없는 컬럼
'''
4-2. 식품섭취빈도조사 (19~64세)
'''
young41 =  ['FS_ffq', 'FS_CHANG', 'FS_CHANG_O', 'FS_MEAL', 'FS_MEAL_O', \
    'FF_RICE', 'FA_RICE', 'FF_BARLEY', 'FA_BARLEY', 'FF_BIBIM', 'FA_BIBIM', \
    'FF_GIMBAB', 'FA_GIMBAB', 'FF_CURRY', 'FA_CURRY', \
    'FF_INSTNO', 'FA_INSTNO', 'FF_WHNO', 'FA_WHNO', 'FF_CHNO', 'FA_CHNO', \
    'FF_BUNO', 'FA_BUNO', 'FF_S_RCAK', 'FA_S_RCAK', 'FF_DUMP', 'FA_DUMP', \
    'FF_BRE', 'FA_BRE', 'FF_BUTTER', 'FA_BUTTER', 'FF_JAM', 'FA_JAM', \
    'FF_RB_BRE', 'FA_RB_BRE', 'FF_CAKE', 'FA_CAKE', 'FF_PIZZA', 'FA_PIZZA', \
    'FF_HAMBER', 'FA_HAMBER', 'FF_RCAK', 'FA_RCAK', 'FF_F_RCAK', 'FA_F_RCAK', \
    'FF_CEREAL', 'FA_CEREAL', 'FF_T_BEEF', 'FA_T_BEEF', 'FF_T_POTA', 'FA_T_POTA', \
    'FF_T_LOAC', 'FA_T_LOAC', 'FF_J_POLL', 'FA_J_POLL', 'FF_S_SWED', 'FA_S_SWED', \
    'FF_S_BEEF', 'FA_S_BEEF', 'FF_S_POLL', 'FA_S_POLL', 'FF_S_SOYP', 'FA_S_SOYP', \
    'FF_J_SOYP', 'FA_J_SOYP', 'FF_J_KIMC', 'FA_J_KIMC', 'FF_J_BUDA', 'FA_J_BUDA', \
    'FF_J_BNCD', 'FA_J_BNCD', 'FF_BNCURD', 'FA_BNCURD', 'FF_S_BEAN', 'FA_S_BEAN', \
    'FF_F_EGG', 'FA_F_EGG', 'FF_S_EGG', 'FA_S_EGG', 'FF_R_PORK', 'FA_R_PORK', \
    'FF_S_PORK', 'FA_S_PORK', 'FF_F_PORK', 'FA_F_PORK', 'FF_C_PORK', 'FA_C_PORK', \
    'FF_R_BEEF', 'FA_R_BEEF', 'FF_F_BEEF', 'FA_F_BEEF', 'FF_HAM', 'FA_HAM'
    'FF_PORKBY', 'FA_PORKBY', 'FF_T_CHIC', 'FA_T_CHIC', 'FF_S_CHIC', 'FA_S_CHIC', \
    'FF_F_CHIC', 'FA_F_CHIC', 'FF_R_DUCK', 'FA_R_DUCK', 'FF_MACKER', 'FA_MACKER', \
    'FF_HAIRT', 'FA_HAIRT', 'FF_ANCH', 'FA_ANCH', 'FF_SQUID', 'FA_SQUID', \
    'FF_SCRAB', 'FA_SCRAB', 'FF_SFISH', 'FA_SFISH', 'FF_FPASTE', 'FA_FPASTE', \
    'FF_SPROU', 'FA_SPROU', 'FF_SPINAC', 'FA_SPINAC', 'FF_BELLFI', 'FA_BELLFI', \
    'FF_PUMPKI', 'FA_PUMPKI', 'FF_OVEG', 'FA_OVEG', 'FF_CUCUMB', 'FA_CUCUMB', \
    'FF_RADI', 'FA_RADI', 'FF_VSALAD', 'FA_VSALAD', 'FF_GREENO', 'FA_GREENO', \
    'FF_RAWVEG', 'FA_RAWVEG', 'FF_BROCOL', 'FA_BROCOL', 'FF_GARLIC', 'FA_GARLIC', \
    'FF_FER_BN', 'FA_FER_BN', 'FF_KIMCHI', 'FA_KIMCHI', 'FF_OKIMCH', 'FA_OKIMCH', \
    'FF_SVEG', 'FA_SVEG', 'FF_ROOT', 'FA_ROOT', 'FF_PCAKE', 'FA_PCAKE', \
    'FF_F_VEG', 'FA_F_VEG', 'FF_MUSHRO', 'FA_MUSHRO', 'FF_LAV', 'FA_LAV', \
    'FF_GLAV', 'FA_GLAV', 'FF_F_SWED', 'FA_F_SWED', 'FF_F_POTA', 'FA_F_POTA', \
    'FF_S_POTA', 'FA_S_POTA', 'FF_SWPOTA', 'FA_SWPOTA', 'FF_CORN', 'FA_CORN', \
    'FF_MILK', 'FA_MILK', 'FF_MILK', 'FA_MILK', 'FS_MILK', 'FF_L_YOGU', 'FA_L_YOGU', \
    'FF_C_YOGU', 'FA_C_YOGU', 'FF_BN_MILK', 'FA_BN_MILK', 'FS_FRUIT', \
    'FF_STRAW', 'FA_STRAW', 'FF_STRAW_YR', 'FS_TOMATO', 'FF_TOMATO', 'FF_TOMATO_YR', 'FA_TOMATO', \
    'FS_MMELON', 'FF_MMELON', 'FF_MMELON_YR', 'FA_MMELON', \
    'FS_WMELON', 'FF_WMELON', 'FF_WMELON_YR', 'FA_WMELON', \
    'FS_PEACH', 'FF_PEACH', 'FF_PEACH_YR', 'FA_PEACH', \
    'FS_GRAPE', 'FF_GRAPE', 'FF_GRAPE_YR', 'FA_GRAPE', \
    'FS_APPLE', 'FF_APPLE', 'FF_APPLE_YR', 'FA_APPLE', \
    'FS_PEAR', 'FF_PEAR', 'FF_PEAR_YR', 'FA_PEAR', \
    'FS_PERS', 'FF_PERS', 'FF_PERS_YR', 'FA_PERS', \
    'FS_TANG', 'FF_TANG', 'FF_TANG_YR', 'FA_TANG', \
    'FS_BANANA', 'FF_BANANA', 'FF_BANANA_YR', 'FA_BANANA', \
    'FS_CITRUS', 'FF_CITRUS', 'FF_CITRUS_YR', 'FA_CITRUS', \
    'FS_KIWI', 'FF_KIWI', 'FF_KIWI_YR', 'FA_KIWI', \
    'FF_COFFEE', 'FA_COFFEE', 'FS_COFFEE', 'FF_CREAM', 'FA_CREAM', 'FF_SUGAR', 'FA_SUGAR'\
    'FF_TEA', 'FA_TEA', 'FF_SODA', 'FA_SODA', 'FF_FJUICE', 'FA_FJUICE', \
    'FF_GBAVER', 'FA_GBAVER', 'FF_SNACK', 'FA_SNACK', 'FF_COOKIE', 'FA_COOKIE', \
    'FF_CHOCO', 'FA_CHOCO', 'FF_ICECM', 'FA_ICECM', 'FF_PEANUT', 'FA_PEANUT', \
    'FF_CHNUT', 'FA_CHNUT', 'FF_SOJU', 'FA_SOJU', 'FS_SOJU', 'FF_BEER', 'FA_BEER', 'FS_BEER', \
    'FF_RWINE', 'FA_RWINE', 'FS_RWINE', \


    'FQ_RICE', 'FQ_BARLEY', 'FQ_BIBIM', 'FQ_GIMBAB', 'FQ_CURRY', \
    'FQ_INSTNO', 'FQ_WHNO', 'FQ_CHNO', 'FQ_BUNO', 'FQ_S_RCAK', \
    'FQ_DUMP', 'FQ_BRE', 'FQ_BUTTER', 'FQ_JAM', 'FQ_RB_BRE', 'FQ_CAKE', 'FQ_PIZZA', \
    'FQ_HAMBER', 'FQ_RCAK', 'FQ_F_RCAK', 'FQ_CEREAL', 'FQ_T_BEEF', \
    'FQ_T_POTA', 'FQ_T_LOAC', 'FQ_J_POLL', 'FQ_S_SWED', 'FQ_S_BEEF', \

    'FQ_S_POLL', 'FQ_S_SOYP', 'FQ_J_SOYP', 'FQ_J_KIMC', 'FQ_J_BUDA', \
    'FQ_J_BNCD', 'FQ_BNCURD', 'FQ_S_BEAN', 'FQ_F_EGG', 'FQ_S_EGG', \
    'FQ_R_PORK', 'FQ_S_PORK', 'FQ_F_PORK', 'FQ_C_PORK', 'FQ_R_BEEF', \
    'FQ_F_BEEF', 'FQ_HAM', 'FQ_PORKBY', 'FQ_T_CHIC', 'FQ_S_CHIC', \
    'FQ_F_CHIC', 'FQ_R_DUCK', 'FQ_MACKER', 'FQ_HAIRT', 'FQ_ANCH', \

    'FQ_SQUID', 'FQ_SCRAB', 'FQ_SFISH', 'FQ_FPASTE', 'FQ_SPROU', \
    'FQ_SPINAC', 'FQ_BELLFI', 'FQ_PUMPKI', 'FQ_OVEG', 'FQ_CUCUMB', \
    'FQ_RADI', 'FQ_VSALAD', 'FQ_GREENO', 'FQ_RAWVEG', 'FQ_BROCOL', \
    'FQ_GARLIC', 'FQ_FER_BN', 'FQ_KIMCHI', 'FQ_OKIMCH', 'FQ_SVEG', \
    'FQ_ROOT', 'FQ_PCAKE', 'FQ_F_VEG', 'FQ_MUSHRO', 'FQ_LAV', \

    'FQ_GLAV', 'FQ_F_SWED', 'FQ_F_POTA', 'FQ_S_POTA', 'FQ_SWPOTA', \
    'FQ_CORN', 'FQ_MILK', 'FQ_L_YOGU', 'FQ_C_YOGU', 'FQ_BN_MILK', \
    'FQ_STRAW', 'FQ_TOMATO', 'FQ_MMELON', 'FQ_WMELON', 'FQ_PEACH', \
    'FQ_GRAPE', 'FQ_APPLE', 'FQ_PEAR', 'FQ_PERS', 'FQ_TANG', \
    'FQ_BANANA', 'FQ_CITRUS', 'FQ_KIWI', 'FQ_COFFEE', 'FQ_CREAM', 'FQ_SUGAR', 'FQ_TEA', \

    'FQ_SODA', 'FQ_FJUICE', 'FQ_GBAVER', 'FQ_SNACK', 'FQ_COOKIE', \
    'FQ_CHOCO', 'FQ_ICECM', 'FQ_PEANUT', 'FQ_CHNUT', 'FQ_SOJU', \
    'FQ_BEER', 'FQ_RWINE', \
    
    'FQ_EN', 'FQ_PROT', 'FQ_FAT', 'FQ_SFA', 'FQ_MUFA', \
    'FQ_PUFA', 'FQ_N3', 'FQ_N6', 'FQ_CHOL', 'FQ_CHO', \
    'FQ_TDF', 'FQ_CA', 'FQ_PHOS', 'FQ_FE', 'FQ_NA', \
    'FQ_K', 'FQ_VA', 'FQ_CAROT', 'FQ_RETIN', 'FQ_B1', \
    'FQ_B2', 'FQ_NIAC', 'FQ_VITC']
print('young41 의 갯수 : ' + str(len(young41)))

young41 의 갯수 : 407

In [238]:
# 4-3-2.식품섭취조사 - 가공자료(영양소 섭취량) + 4.4. 식품안정성조사
# ### 제거 할 값이 없는 컬럼
variable_432 = ['N_INTK', 'N_EN', 'N_WATER', 'N_PROT', \
    'N_FAT', 'N_SFA', 'N_MUFA', 'N_PUFA', 'N_N3', 'N_N6', 'N_CHOL', 'N_CHO', \
    'N_TDF', 'N_SUGAR', 'N_CA', 'N_PHOS', 'N_FE', 'N_NA', 'N_K', 'N_VA', 'N_VA_RAE', \
    'N_CAROT', 'N_RETIN', 'N_B1', 'N_B2', 'N_NIAC', 'N_FOLATE', 'N_VITC', \
    'LF_secur_y', 'HEI', 'HEI_BR', 'HEI_CEREAL', 'HEI_TFRUIT', 'HEI_FFRUIT', \
    'HEI_TVEG', 'HEI_VEG', 'HEI_PROTF', 'HEI_DAIRY', 'HEI_SFA', 'HEI_NA', \
    'HEI_SWEET', 'HEI_CHO', 'HEI_FAT', 'HEI_EN', \
    'LF_SECUR_Y', 'LF_CHIL', 'LF_SECUR', 'LF_SECUR_G']
print('variable_432   의 갯수 : ' + str(len(variable_432)))

### 8, 9 제거 할 컬럼
variable_432_1 = ['LF_BUYER', 'LF_SAFE', 'LF_safe', \
    'LF_S2', 'LF_S3', 'LF_S4', 'LF_S5', 'LF_S5_1', \
    'LF_S6', 'LF_S7', 'LF_S8', 'LF_S9', 'LF_S9_1', \
    'LF_S10', 'LF_S11', 'LF_S12', 'LF_S13', 'LF_S14', 'LF_S14_1', \
    'LF_S15', 'LF_S16']
print('variable_432_1 의 갯수 : ' + str(len(variable_432_1)))

variable_432   의 갯수 : 48
variable_432_1 의 갯수 : 21

# 컬럼 확인해보기

In [260]:
# 정리할 컬럼들 묶어서 확인하기
remove_0 = variable_1 + variable_1wt + variable_21 + variable_23 + \
    variable_26 + variable_29 + variable_210 + variable_212 + \
    variable_214 + variable_215 + variable_216 + variable_31 + \
    variable_38 + variable_41 + variable_432
remove_1 = variable_21_1 + variable_23_1 + variable_26_1 + variable_29_1 + \
    variable_210_1 + variable_212_1 + variable_214_1 + variable_215_1 + \
    variable_216_1 + variable_31_1 + variable_38_1 + variable_41_1 + variable_432_1
remove_2 = variable_21_2 + variable_23_2 + variable_26_2 + variable_29_2 + \
    variable_212_2 + variable_214_2 + variable_215_2 + variable_216_2 + \
    variable_31_2 + variable_38_2 + variable_41_2
remove_3 = variable_21_3 + variable_23_3 + variable_26_3  + variable_29_3 + \
    variable_210_3 + variable_212_3 + variable_214_3 + variable_216_3 + \
    variable_38_3 + variable_41_3
remove_4 = variable_23_4 + variable_26_4 + variable_212_4 + variable_214_4 + \
    variable_216_4 + variable_38_4
remove_5 = variable_38_5
remove_6 = variable_21_6
remove_f32 = variable_38_32
remove_4s = variable_41_4_3
remove_2s = variable_41_2_1
remove_col = young21 + young29 + young214 + young41

print('1. remove_0 : ' + str(len(remove_0)))
print('2. remove_1 : ' + str(len(remove_1)))
print('3. remove_2 : ' + str(len(remove_2)))
print('4. remove_3 : ' + str(len(remove_3)))
print('5. remove_4 : ' + str(len(remove_4)))
print('6. remove_5 : ' + str(len(remove_5)))
print('7. remove_6 : ' + str(len(remove_6)))
print('8. remove_f32 : ' + str(len(remove_f32)))
print('9. remove_4s : ' + str(len(remove_4s)))
print('10. remove_2s : ' + str(len(remove_2s)))
print('11. remove_col : ' + str(len(remove_col)))

remove_all = remove_0 + remove_1 + remove_2 + remove_3 + remove_4 + \
    remove_5 + remove_6 + remove_f32 + remove_4s + remove_2s + remove_col
print('-------------ALL--------------정리할 컬럼 수')
print('all. remove_all : ' + str(len(remove_all)))

1. remove_0 : 375
2. remove_1 : 527
3. remove_2 : 106
4. remove_3 : 86
5. remove_4 : 20
6. remove_5 : 2
7. remove_6 : 2
8. remove_f32 : 4
9. remove_4s : 1
10. remove_2s : 1
11. remove_col : 424
-------------ALL--------------정리할 컬럼 수
all. remove_all : 1548

In [408]:
# 10개 파일 다 읽기
age16_1 = pd.read_csv('data/age16_1.csv', index_col = 0)
age17_1 = pd.read_csv('data/age17_1.csv', index_col = 0)
age18_1 = pd.read_csv('data/age18_1.csv', index_col = 0)
age19_1 = pd.read_csv('data/age19_1.csv', index_col = 0)
age20_1 = pd.read_csv('data/age20_1.csv', index_col = 0)

age16_2 = pd.read_csv('data/age16_2.csv', index_col = 0)
age17_2 = pd.read_csv('data/age17_2.csv', index_col = 0)
age18_2 = pd.read_csv('data/age18_2.csv', index_col = 0)
age19_2 = pd.read_csv('data/age19_2.csv', index_col = 0)
age20_2 = pd.read_csv('data/age20_2.csv', index_col = 0)

C:\Users\USER\AppData\Local\Temp\ipykernel_23392\776394133.py:2: DtypeWarning: Columns (49,181,428,469,616) have mixed types. Specify dtype option on import or set low_memory=False.
  age16_1 = pd.read_csv('data/age16_1.csv', index_col = 0)
C:\Users\USER\AppData\Local\Temp\ipykernel_23392\776394133.py:3: DtypeWarning: Columns (264,402,522) have mixed types. Specify dtype option on import or set low_memory=False.
  age17_1 = pd.read_csv('data/age17_1.csv', index_col = 0)
C:\Users\USER\AppData\Local\Temp\ipykernel_23392\776394133.py:4: DtypeWarning: Columns (44,127,291,312,328,409,528,543) have mixed types. Specify dtype option on import or set low_memory=False.
  age18_1 = pd.read_csv('data/age18_1.csv', index_col = 0)
C:\Users\USER\AppData\Local\Temp\ipykernel_23392\776394133.py:5: DtypeWarning: Columns (44,45,99,639) have mixed types. Specify dtype option on import or set low_memory=False.
  age19_1 = pd.read_csv('data/age19_1.csv', index_col = 0)
C:\Users\USER\AppData\Local\Temp\ipykernel_23392\776394133.py:6: DtypeWarning: Columns (121,570) have mixed types. Specify dtype option on import or set low_memory=False.
  age20_1 = pd.read_csv('data/age20_1.csv', index_col = 0)

In [195]:
# 컬럼들 리스트로 확인하기
age16_1_col = list(age16_1.columns)
age17_1_col = list(age17_1.columns)
age18_1_col = list(age18_1.columns)
age19_1_col = list(age19_1.columns)
age20_1_col = list(age20_1.columns)

age16_2_col = list(age16_2.columns)
age17_2_col = list(age17_2.columns)
age18_2_col = list(age18_2.columns)
age19_2_col = list(age19_2.columns)
age20_2_col = list(age20_2.columns)

In [284]:
# thiscol은 그냥 dataframe 집어넣으면 됨
def check_this_col(thiscol):
    global this_col
    this_col = list(thiscol.columns)
    cnt_y = 0
    cnt_n = 0
    pre_len = len(this_col)

    for i in remove_all:
        try:
            this_col.remove(i)
            cnt_y += 1
        except ValueError:
            cnt_n += 1

    print('컬럼 수 {} 개 중 {}개 확인 \t 남은컬럼 {}개'.format(pre_len, cnt_y, len(this_col)))

In [279]:
# 놓친 컬럼이 있을까?
print('---------age16_1 ---------')
check_this_col(age16_1)
print('---------age17_1 ---------')
check_this_col(age17_1)
print('---------age18_1 ---------')
check_this_col(age18_1)
print('---------age19_1 ---------')
check_this_col(age19_1)
print('---------age20_1 ---------')
check_this_col(age20_1)
print('--------------------------')
print('---------age16_2 ---------')
check_this_col(age16_2)
print('---------age17_2 ---------')
check_this_col(age17_2)
print('---------age18_2 ---------')
check_this_col(age18_2)
print('---------age19_2 ---------')
check_this_col(age19_2)
print('---------age20_2 ---------')
check_this_col(age20_2)

---------age16_1 ---------
컬럼 수 772 개 중 772개 확인 	 남은컬럼 0개
---------age17_1 ---------
컬럼 수 830 개 중 830개 확인 	 남은컬럼 0개
---------age18_1 ---------
컬럼 수 758 개 중 758개 확인 	 남은컬럼 0개
---------age19_1 ---------
컬럼 수 793 개 중 793개 확인 	 남은컬럼 0개
---------age20_1 ---------
컬럼 수 724 개 중 724개 확인 	 남은컬럼 0개
--------------------------
---------age16_2 ---------
컬럼 수 29 개 중 29개 확인 	 남은컬럼 0개
---------age17_2 ---------
컬럼 수 29 개 중 29개 확인 	 남은컬럼 0개
---------age18_2 ---------
컬럼 수 29 개 중 29개 확인 	 남은컬럼 0개
---------age19_2 ---------
컬럼 수 29 개 중 29개 확인 	 남은컬럼 0개
---------age20_2 ---------
컬럼 수 29 개 중 29개 확인 	 남은컬럼 0개

- T_balance  
19년(8차)(age19_1) 에 T_balance 라는 컬럼이 존재하는데 이용지침서에 없음.  
값을 살펴봤을 때 0, 1 밖에 없어서 처리하지 않았음

# 진짜 8 , 9 같은 값들을 제거 해 보자

0. remove_0  
제거 할 필요 X
1. remove_1  
8, 9 제거
2. remove_2  
88, 99 제거
3. remove_3  
888, 999 제거
4. remove_4  
8888, 9999 제거
5. remove_5  
88888, 99999 제거
6. remove_6  
888888, 999999 제거
7. remove_f32  
888.88, 999.99 제거
8. remove_4s  
8881, 8882, 8883 제거
9. remove_2s  
98, 99 제거

In [365]:
# remove 처리 할 컬럼들
print('0. remove_0 : ' + str(len(remove_0)))
print('1. remove_1 : ' + str(len(remove_1)))
print('2. remove_2 : ' + str(len(remove_2)))
print('3. remove_3 : ' + str(len(remove_3)))
print('4. remove_4 : ' + str(len(remove_4)))
print('5. remove_5 : ' + str(len(remove_5)))
print('6. remove_6 : ' + str(len(remove_6)))
print('7. remove_f32 : ' + str(len(remove_f32)))
print('8. remove_4s : ' + str(len(remove_4s)))
print('9. remove_2s : ' + str(len(remove_2s)))
print('10. remove_col : ' + str(len(remove_col)))

# remove_col 은 노인이 아닌 의미 없는 컬럼이라서 컬럼을 삭제해야함
# 혹시나 값이 든게 있나 싶으니 먼저 0~9부터 처리.

0. remove_0 : 375
1. remove_1 : 527
2. remove_2 : 106
3. remove_3 : 86
4. remove_4 : 20
5. remove_5 : 2
6. remove_6 : 2
7. remove_f32 : 4
8. remove_4s : 1
9. remove_2s : 1
10. remove_col : 424

In [413]:
def remove89(df):
    passed1, passed2, passed3, passed4, passed5, passed6, passed7, passed8, passed9= 0, 0, 0, 0, 0, 0, 0, 0, 0
    pre_df = df.copy()
    # 1
    for i in remove_1:
        try:
            pre_df[i] = df[i].replace([8, 9], np.nan)
        except KeyError:
            passed1 += 1
    # 2
    for i in remove_2:
        try:
            pre_df[i] = df[i].replace([88, 99], np.nan)
        except KeyError:
            passed2 += 1
    # 3
    for i in remove_3:
        try:
            pre_df[i] = df[i].replace([888, 999], np.nan)
        except KeyError:
            passed3 += 1
    # 4
    for i in remove_4:
        try:
            pre_df[i] = df[i].replace([8888, 9999], np.nan)
        except KeyError:
            passed4 += 1
    # 5
    for i in remove_5:
        try:
            pre_df[i] = df[i].replace([88888, 99999], np.nan)
        except KeyError:
            passed5 += 1
    # 6
    for i in remove_6:
        try:
            pre_df[i] = df[i].replace([888888, 999999], np.nan)
        except KeyError:
            passed6 += 1
    # 7
    for i in remove_f32:
        try:
            pre_df[i] = df[i].replace([888.88, 999.99], np.nan)
        except KeyError:
            passed7 += 1
    # 8
    for i in remove_4s:
        try:
            pre_df[i] = df[i].replace([8881, 8882, 8883], np.nan)
        except KeyError:
            passed8 += 1
    # 9
    for i in remove_2s:
        try:
            pre_df[i] = df[i].replace([98, 99], np.nan)
        except KeyError:
            passed9 += 1


    return pre_df

In [414]:
pre_age16_1 = remove89(age16_1)
pre_age16_1

,mod_d,id,ID_fam,year,region,town_t,apt_t,psu,sex,age,...,HEI_TVEG,HEI_VEG,HEI_PROTF,HEI_DAIRY,HEI_SFA,HEI_NA,HEI_SWEET,HEI_CHO,HEI_FAT,HEI_EN
12,b'2022.03.08',b'A651228902',b'A6512289',2016.0,1.0,1.0,2.0,b'A651',2.0,78.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55,b'2022.03.08',b'A651417601',b'A6514176',2016.0,1.0,1.0,2.0,b'A651',1.0,80.0,...,5.000000,3.092948,10.000000,10.00000,9.986004,4.667112,10.000000,5.000000,5.000000,5.000000
69,b'2022.03.08',b'A652228901',b'A6522289',2016.0,1.0,1.0,2.0,b'A652',1.0,66.0,...,1.788935,0.304439,10.000000,0.00000,10.000000,5.713150,10.000000,1.264658,2.250121,0.000000
101,b'2022.03.08',b'A653184701',b'A6531847',2016.0,1.0,1.0,1.0,b'A653',2.0,75.0,...,0.373081,0.746163,3.503593,0.00000,10.000000,10.000000,10.000000,1.557652,5.000000,0.000000
111,b'2022.03.08',b'A653235705',b'A6532357',2016.0,1.0,1.0,1.0,b'A653',2.0,79.0,...,1.791667,0.000000,2.775250,1.77434,10.000000,10.000000,10.000000,0.000000,5.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,b'2022.03.08',b'R654271406',b'R6542714',2016.0,8.0,2.0,2.0,b'R654',2.0,66.0,...,2.164839,1.962809,10.000000,0.00000,10.000000,10.000000,10.000000,5.000000,5.000000,1.187048
8124,b'2022.03.08',b'R654279901',b'R6542799',2016.0,8.0,2.0,2.0,b'R654',2.0,80.0,...,2.194360,3.736339,10.000000,0.00000,7.612126,10.000000,3.579468,0.000000,1.531671,0.000000
8133,b'2022.03.08',b'R654308803',b'R6543088',2016.0,8.0,2.0,2.0,b'R654',1.0,80.0,...,2.788147,2.068826,9.500000,0.00000,10.000000,10.000000,10.000000,1.432012,3.661889,5.000000
8145,b'2022.03.08',b'R654353001',b'R6543530',2016.0,8.0,2.0,2.0,b'R654',1.0,75.0,...,5.000000,5.000000,3.700000,0.00000,10.000000,10.000000,10.000000,4.410503,5.000000,5.000000
8146,b'2022.03.08',b'R654353002',b'R6543530',2016.0,8.0,2.0,2.0,b'R654',2.0,72.0,...,5.000000,5.000000,10.000000,0.00000,10.000000,10.000000,10.000000,5.000000,5.000000,5.000000

In [415]:
# 임의 컬럼으로 확인
age16_1['EC1_1'].unique()

array([ 2.,  1.,  9., nan])

In [416]:
pre_age16_1['EC1_1'].unique()

array([ 2.,  1., nan])

In [417]:
pre_age16_1 = remove89(age16_1)
pre_age17_1 = remove89(age17_1)
pre_age18_1 = remove89(age18_1)
pre_age19_1 = remove89(age19_1)
pre_age20_1 = remove89(age20_1)

pre_age16_2 = remove89(age16_2)
pre_age17_2 = remove89(age17_2)
pre_age18_2 = remove89(age18_2)
pre_age19_2 = remove89(age19_2)
pre_age20_2 = remove89(age20_2)

In [424]:
pre_age16_1.to_csv('data\pre_age16_1.csv', index=False)
pre_age17_1.to_csv('data\pre_age17_1.csv', index=False)
pre_age18_1.to_csv('data\pre_age18_1.csv', index=False)
pre_age19_1.to_csv('data\pre_age19_1.csv', index=False)
pre_age20_1.to_csv('data\pre_age20_1.csv', index=False)

pre_age16_2.to_csv('data\pre_age16_2.csv', index=False)
pre_age17_2.to_csv('data\pre_age17_2.csv', index=False)
pre_age18_2.to_csv('data\pre_age18_2.csv', index=False)
pre_age19_2.to_csv('data\pre_age19_2.csv', index=False)
pre_age20_2.to_csv('data\pre_age20_2.csv', index=False)