In [54]:
import pandas as pd
concat_age1 = pd.read_csv('concat_age1.csv', index_col = 0)
concat_age2 = pd.read_csv('concat_age2.csv', index_col = 0)

C:\Users\User\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (45,183,193,200,249,274,374,385,425,568,629,687,692,693,699,701,702,703,704,708,710,712,730,731,738,740,744,745,746,751,783,820,823,842,845,881) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [55]:
# concat_age1 --> 유병여부 컬럼을 제외한 나머지 컬럼들로 구성된 실제 데이터(5개년치)
concat_age1

,ID,ID_FAM,REGION,TOWN_T,APT_T,PSU,SEX,AGE,INCM,HO_INCM,...,LF_SECUR_G,AC3_1_03,AC3_2_03,AC8_1_03,BS12_47_4,HE_PLS_30,HE_UCREA_ETC,MO4_17_1,MO4_17_2,T_TYMP_DIS
0,b'A651228902',b'A6512289',1.0,1.0,2.0,b'A651',2.0,78.0,3.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,b'A651417601',b'A6514176',1.0,1.0,2.0,b'A651',1.0,80.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,b'A652228901',b'A6522289',1.0,1.0,2.0,b'A652',1.0,66.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,b'A653184701',b'A6531847',1.0,1.0,1.0,b'A653',2.0,75.0,2.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,b'A653235705',b'A6532357',1.0,1.0,1.0,b'A653',2.0,79.0,4.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8398,b'R804176202',b'R8041762',8.0,1.0,2.0,b'R804',1.0,66.0,2.0,2.0,...,1.0,NaN,NaN,NaN,NaN,34.0,NaN,1.0,0.0,0.0
8399,b'R804205101',b'R8042051',8.0,1.0,2.0,b'R804',1.0,75.0,4.0,2.0,...,1.0,NaN,NaN,NaN,NaN,31.0,NaN,0.0,0.0,0.0
8400,b'R804205102',b'R8042051',8.0,1.0,2.0,b'R804',2.0,65.0,3.0,2.0,...,1.0,NaN,NaN,NaN,NaN,32.0,NaN,NaN,NaN,0.0
8401,b'R804344501',b'R8043445',8.0,1.0,2.0,b'R804',2.0,65.0,2.0,2.0,...,1.0,NaN,NaN,NaN,NaN,38.0,NaN,1.0,1.0,0.0
8402,b'R804371701',b'R8043717',8.0,1.0,2.0,b'R804',1.0,65.0,2.0,2.0,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,0.0

In [56]:
# concat_age2 --> 유병여부 컬럼으로 구성된 실제 데이터(5개년치)
concat_age2

,ID,DI1_PR,DI2_PR,DI3_PR,DI4_PR,DI5_PR,DM2_PR,DM3_PR,DM4_PR,DJ2_PR,...,DC1_PR,DC2_PR,DC3_PR,DC4_PR,DC5_PR,DC6_PR,DC7_PR,DK8_PR,DK9_PR,DK4_PR
0,b'A651228902',1.0,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
1,b'A651417601',1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,b'A652228901',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,b'A653184701',NaN,1.0,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,b'A653235705',1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8398,b'R804176202',1.0,1.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8399,b'R804205101',0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8400,b'R804205102',NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8401,b'R804344501',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8402,b'R804371701',NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [57]:
# same_code_2 --> 최종 변수설명서
same_code_2 = pd.read_csv('C:/Users/User/VS_code/sas_view/code/same_code_2.csv', index_col = 0)

In [58]:
same_code_2

,변수명,변수설명7,변수설명8
0,mod_d,최종 DB 수정일,최종 DB 수정일
1,ID,개인 아이디,개인 아이디
2,ID_fam,가구 아이디,가구 아이디
3,year,조사연도,조사연도
4,region,17개 시도,17개 시도
...,...,...,...
747,T_NQ_OCP,작업장 내 소음노출 경험,직업적 소음노출
748,HE_DM,당뇨병 유병여부(19세이상),당뇨병 유병여부(19세이상)
749,Total_slp_wk,(만12세이상) 주중 하루 평균 수면시간,(만12세이상) 주중(또는 일하는 날) 하루 평균 수면 시간
750,Total_slp_wd,(만12세이상) 주말 하루 평균 수면시간,"(만12세이상) 주말(또는 일하지 않는 날, 일하지 않는 전날) 하루 평균 수면 시간"
751,HE_UCREA,요크레아티닌,요크레아티닌

In [59]:
col_up = []
for i in list(same_code_2['변수명'].values):
    col_up.append(i.upper())

len(col_up)

752

In [61]:
for i in ['MOD_D', 'YEAR', 'AGE_MONTH', 'DI1_PR', 'DI2_PR', 'DI4_PR', 'DI5_PR', 'DI6_PR', 'DM3_PR', 'DM4_PR', 'DC1_PR', 'DF2_PR', 'DJ6_PR', 'DH4_PR', 'AC8_1_04', 'AC8_1_05', 'BA1_1', 'BA1_2', 'HE_DPRG', 'HE_WT_PCT', 'HE_BMI_PCT', 'Y_BTH_WT', 'Y_MTM_YN', 'Y_MTM_S1', 'Y_MTM_S2', 'Y_MTM_D1', 'Y_MTM_D2', 'Y_FM_YN', 'Y_FM_S1', 'Y_FM_S2', 'Y_FM_D1', 'Y_FM_D2', 'Y_MLK_ST', 'Y_WN_ST', 'Y_SUP_YN', 'Y_SUP_KD1', 'Y_SUP_KD3', 'Y_SUP_KD4', 'Y_SUP_KD7', 'N_PRG', 'N_BFD_Y', 'N_MEAL', 'N_MEAL_T', 'N_MEAL_P', 'N_MTYPE', 'N_MEAL_W', 'N_DNAME', 'N_DCODE', 'N_CD_VOL', 'N_CD_WT', 'N_TD_VOL', 'N_TD_WT', 'N_FCODE', 'N_FNAME', 'N_ENAME', 'N_FD_NS', 'N_FM_WT', 'N_PRODUCT', 'N_CNAME', 'N_AP', 'N_FCODE3', 'N_FNAME3', 'NF_INTK', 'NF_INTK3', 'DI3_PR', 'DM2_PR', 'DJ2_PR', 'DJ4_PR', 'DE1_PR', 'DE2_PR', 'DC2_PR', 'DC3_PR', 'DC4_PR', 'DC5_PR', 'DC6_PR', 'DC7_PR', 'DL1_PR', 'DJ8_PR', 'DK8_PR', 'DK9_PR', 'DK4_PR', 'LQ4_17', 'LQ4_18', 'LQ4_19', 'LQ4_20', 'AC3_1_04', 'AC3_1_05', 'AC3_2_04', 'AC3_2_05', 'AC8_1E_01', 'AC8_1E_02', 'AC8_1E_03', 'AC8_1E_04', 'AC8_1E_05', 'BS12_45', 'N_KINDG1', 'NF_EN', 'NF_WATER', 'NF_PROT', 'NF_FAT', 'NF_SFA', 'NF_MUFA', 'NF_PUFA', 'NF_N3', 'NF_N6', 'NF_10_0', 'NF_12_0', 'NF_14_0', 'NF_16_0', 'NF_18_0', 'NF_20_0', 'NF_22_0', 'NF_24_0', 'NF_14_1', 'NF_16_1', 'NF_18_1', 'NF_20_1', 'NF_22_1', 'NF_24_1', 'NF_18_2N6', 'NF_18_3N3', 'NF_18_3N6', 'NF_18_4', 'NF_20_2', 'NF_20_3N6', 'NF_20_4N6', 'NF_20_5N3', 'NF_22_2', 'NF_22_5', 'NF_22_6N3', 'NF_CHOL', 'NF_CHO', 'NF_TDF', 'NF_SUGAR', 'NF_CA', 'NF_PHOS', 'NF_FE', 'NF_NA', 'NF_K', 'NF_VA_RAE', 'NF_CAROT', 'NF_RETIN', 'NF_B1', 'NF_B2', 'NF_NIAC', 'NF_FOLATE', 'NF_VITC']:
    col_up.remove(i)
len(col_up)

605

In [64]:
real_data1 = concat_age1[col_up]
real_data2 = concat_age2

In [66]:
real_data1.to_csv('real_data1.csv', encoding='cp949')
real_data2.to_csv('real_data2.csv', encoding='cp949')

In [106]:
col_up

['ID',
 'ID_FAM',
 'REGION',
 'TOWN_T',
 'APT_T',
 'PSU',
 'SEX',
 'AGE',
 'INCM',
 'HO_INCM',
 'INCM5',
 'HO_INCM5',
 'EDU',
 'OCCP',
 'WT_HS',
 'WT_ITVEX',
 'WT_PFT',
 'WT_NTR',
 'WT_TOT',
 'WT_PFNT',
 'KSTRATA',
 'CFAM',
 'GENERTN',
 'ALLOWNC',
 'LIVE_T',
 'AINC',
 'MARRI_1',
 'MARRI_2',
 'FAM_RELA',
 'TINS',
 'ID_F',
 'ID_M',
 'D_2_WK',
 'DI1_DG',
 'DI1_AG',
 'DI1_PT',
 'DI1_2',
 'DI2_AG',
 'DI2_2',
 'DI3_AG',
 'DI3_2',
 'DI4_DG',
 'DI4_PT',
 'DI5_DG',
 'DI5_AG',
 'DI5_PT',
 'DI6_DG',
 'DI6_AG',
 'DI6_PT',
 'DM1_DG',
 'DM1_PR',
 'DM1_PT',
 'DM2_AG',
 'DM3_DG',
 'DM3_AG',
 'DM3_PT',
 'DM4_DG',
 'DM4_AG',
 'DM4_PT',
 'DJ2_AG',
 'DJ4_DG',
 'DJ4_AG',
 'DJ4_PT',
 'DJ4_3',
 'DE1_DG',
 'DE1_AG',
 'DE1_3',
 'DE1_4',
 'DE2_AG',
 'DC1_DG',
 'DC1_AG',
 'DC1_PT',
 'DC2_DG',
 'DC2_AG',
 'DC3_DG',
 'DC3_AG',
 'DC4_DG',
 'DC4_AG',
 'DC5_DG',
 'DC5_AG',
 'DC6_DG',
 'DC6_AG',
 'DC7_DG',
 'DC7_AG',
 'DC11_DG',
 'DC11_AG',
 'DC12_DG',
 'DC12_AG',
 'DF2_AG',
 'DL1_DG',
 'DL1_AG',
 'DJ8_DG',
 'DJ8_AG',
 'DJ6_DG',
 'DJ6_AG',
 'DJ6_PT',
 'DH4_DG',
 'DH4_AG',
 'DH4_PT',
 'DK8_AG',
 'DK9_AG',
 'DK4_AG',
 'M_2_YR',
 'MT_NONTRT',
 'BH2_61',
 'LQ4_00',
 'LQ4_01',
 'LQ4_02',
 'LQ4_03',
 'LQ4_04',
 'LQ4_05',
 'LQ4_06',
 'LQ4_07',
 'LQ4_08',
 'LQ4_09',
 'LQ4_10',
 'LQ4_11',
 'LQ4_12',
 'LQ4_13',
 'LQ4_14',
 'LQ4_15',
 'LQ4_16',
 'LQ4_21',
 'LQ4_22',
 'LQ4_25',
 'LQ4_26',
 'LQ4_27',
 'LQ4_28',
 'LQ4_29',
 'LQ4_23',
 'LQ1_SB',
 'LQ1_MN',
 'LQ2_AB',
 'LQ2_MN',
 'EQ5D',
 'AC3',
 'AC8_1_01',
 'AC8_1_02',
 'AC8_1_03',
 'MH1_YR',
 'MH1_1',
 'MO1_WK',
 'EC1_1',
 'EC_OCCP',
 'EC_STT_1',
 'EC_WHT_0',
 'EC_WHT_23',
 'EC_WHT_5',
 'EC_LGW_4',
 'EC_LGW_5',
 'EC_PEDU_1',
 'EC_PEDU_2',
 'BO3_01',
 'BO3_03',
 'BO3_14',
 'BO3_07',
 'BO3_09',
 'BO3_10',
 'BD2_31',
 'BD2_32',
 'BD7_4',
 'BD7_61',
 'BD7_62',
 'BD7_63',
 'BD7_64',
 'BD7_65',
 'BD7_66',
 'DR_MONTH',
 'BA2_12',
 'BA2_2_1',
 'BA2_2_2',
 'BA2_2_3',
 'BA2_2_4',
 'BA2_2_5',
 'BA2_2_6',
 'BA2_22',
 'SC_SEATBLT2',
 'BP_PHQ_1',
 'BP_PHQ_2',
 'BP_PHQ_3',
 'BP_PHQ_4',
 'BP_PHQ_5',
 'BP_PHQ_6',
 'BP_PHQ_7',
 'BP_PHQ_8',
 'BP_PHQ_9',
 'BP1',
 'BP5',
 'BP6_10',
 'BP6_2',
 'BP6_31',
 'BP7',
 'MH_STRESS',
 'SM_PRESNT',
 'BE8_1',
 'BE8_2',
 'BE3_31',
 'BE3_32',
 'BE3_33',
 'BE5_1',
 'PA_AEROBIC',
 'LW_MP_E',
 'LW_MP_A',
 'LW_MS_A',
 'LW_BR',
 'LW_BR_CH',
 'LW_BR_DUR',
 'LW_BR_YY',
 'LW_BR_MM',
 'LW_OC',
 'HE_FST',
 'HE_HPDR',
 'HE_DMDR',
 'HE_MENS',
 'HE_PRG',
 'HE_FH',
 'HE_HPFH1',
 'HE_HPFH2',
 'HE_HPFH3',
 'HE_HLFH1',
 'HE_HLFH2',
 'HE_HLFH3',
 'HE_IHDFH1',
 'HE_IHDFH2',
 'HE_IHDFH3',
 'HE_STRFH1',
 'HE_STRFH2',
 'HE_STRFH3',
 'HE_DMFH1',
 'HE_DMFH2',
 'HE_DMFH3',
 'HE_THFH1',
 'HE_THFH2',
 'HE_THFH3',
 'HE_HBFH1',
 'HE_HBFH2',
 'HE_HBFH3',
 'HE_RPLS',
 'HE_MPLS',
 'HE_NARM',
 'HE_SBP1',
 'HE_DBP1',
 'HE_SBP2',
 'HE_DBP2',
 'HE_SBP3',
 'HE_DBP3',
 'HE_SBP',
 'HE_DBP',
 'HE_HP',
 'HE_HT',
 'HE_WT',
 'HE_WC',
 'HE_BMI',
 'HE_OBE',
 'HE_GLU',
 'HE_HBA1C',
 'HE_CHOL',
 'HE_HDL_ST2',
 'HE_TG',
 'HE_LDL_DRCT',
 'HE_HCHOL',
 'HE_HTG',
 'HE_AST',
 'HE_ALT',
 'HE_ALT_ETC',
 'HE_HEPAB',
 'HE_HEPAC',
 'HE_HB',
 'HE_HCT',
 'HE_ANEM',
 'HE_BUN',
 'HE_CREA',
 'HE_WBC',
 'HE_RBC',
 'HE_BPLT',
 'HE_UACID',
 'HE_UACID_ETC',
 'HE_UPH',
 'HE_UNITR',
 'HE_USG',
 'HE_UPRO',
 'HE_UGLU',
 'HE_UKET',
 'HE_UBIL',
 'HE_UBLD',
 'HE_URO',
 'HE_UCOT',
 'HE_UCOT_ETC',
 'HE_UNA',
 'HE_UKAL',
 'HE_UKAL_ETC',
 'HE_FVC',
 'HE_FVCP',
 'HE_FEV1',
 'HE_FEV1P',
 'HE_FEV1FVC',
 'HE_FEV6',
 'HE_FEF25_75',
 'HE_PEF',
 'HE_COPD',
 'HE_COUGH1',
 'HE_COUGH2',
 'HE_SPUT1',
 'HE_SPUT2',
 'HE_PFTDR',
 'HE_PFTAG',
 'HE_PFTTR',
 'HE_PFTHS',
 'OR1',
 'O_PAIN',
 'O_ORTHO',
 'BM1_0',
 'BM1_1',
 'BM1_2',
 'BM1_3',
 'BM1_4',
 'BM1_5',
 'BM1_6',
 'BM1_7',
 'BM1_8',
 'BM2_1',
 'BM2_3',
 'BM2_2',
 'BM2_4',
 'BM13',
 'BM13_1',
 'BM13_2',
 'BM13_3',
 'BM13_4',
 'BM13_5',
 'BM13_6',
 'BM7',
 'O_CHEW_D',
 'BM8',
 'OR1_2',
 'MO4_00',
 'MO4_8',
 'MO4_12',
 'BM14',
 'BM14_1',
 'BM14_2',
 'T_Q_HR',
 'GS_USE',
 'GS_MEA_R_1',
 'GS_MEA_R_2',
 'GS_MEA_R_3',
 'GS_MEA_L_1',
 'GS_MEA_L_2',
 'GS_MEA_L_3',
 'L_BR',
 'L_LN',
 'L_DN',
 'L_BR_FQ',
 'L_LN_FQ',
 'L_DN_FQ',
 'L_OUT_FQ',
 'L_BR_TO',
 'L_BR_WHO',
 'L_LN_TO',
 'L_LN_WHO',
 'L_DN_TO',
 'L_DN_WHO',
 'LS_1YR',
 'LK_EDU',
 'LK_LB_CO',
 'LK_LB_US',
 'LK_LB_IT',
 'LK_LB_EF',
 'N_DIET',
 'N_DIET_WHY',
 'N_DT_DS',
 'N_DT_ETC',
 'N_DUSUAL',
 'N_WAT_C',
 'N_DAY',
 'LF_SECUR_Y',
 'LF_BUYER',
 'LF_SAFE',
 'WT_OE',
 'HOUSE',
 'AINC_UNIT1',
 'AINC_1',
 'NPINS',
 'D_1_1',
 'D_2_1',
 'DI2_DG',
 'DI2_PT',
 'DI3_DG',
 'DI3_PT',
 'DM2_DG',
 'DM2_PT',
 'DJ2_DG',
 'DJ2_PT',
 'DE1_PT',
 'DE1_31',
 'DE1_32',
 'DE1_33',
 'DE1_34',
 'DE1_35',
 'DE2_DG',
 'DE2_PT',
 'DC2_PT',
 'DC3_PT',
 'DC4_PT',
 'DC5_PT',
 'DC6_PT',
 'DC7_PT',
 'DC11_TP',
 'DC11_PR',
 'DC11_PT',
 'DC12_TP',
 'DC12_PR',
 'DC12_PT',
 'DF2_DG',
 'DF2_PT',
 'DL1_PT',
 'DJ8_PT',
 'DK8_DG',
 'DK8_PT',
 'DK9_DG',
 'DK9_PT',
 'DK4_DG',
 'DK4_PT',
 'DF1_YD',
 'DF1_YA',
 'DJ9_YD',
 'DJ9_YA',
 'M_2_RS',
 'M_2_ET',
 'BH9_11',
 'BH1',
 'BH1_1',
 'BH1_2',
 'BH1_3',
 'BH1_8',
 'BH1_6',
 'BH1_7',
 'BH2_62',
 'BH2_63',
 'BH2_66',
 'BH2_67',
 'BH2_64',
 'BH2_65',
 'LQ4_24',
 'LQ_1EQL',
 'LQ_2EQL',
 'LQ_3EQL',
 'LQ_4EQL',
 'LQ_5EQL',
 'AC1_YR',
 'AC3_1_01',
 'AC3_1_02',
 'AC3_1_03',
 'AC3_2_01',
 'AC3_2_02',
 'AC3_2_03',
 'IJ_EXPR',
 'MO1_1',
 'EDUC',
 'GRADUAT',
 'CH2_1',
 'CH2_2',
 'EC_STT_2',
 'EC_WHT_6',
 'EC_LGW_2',
 'BO1',
 'BO1_1',
 'BO1_2',
 'BO1_3',
 'BO2_1',
 'BO3_02',
 'BO3_05',
 'BO3_04',
 'BO3_12',
 'BO3_11',
 'BD1',
 'BD2',
 'BD1_11',
 'BD2_1',
 'BD2_14',
 'BD7_5',
 'BD7_67',
 'BA2_13',
 'BA1_3',
 'SC_SEATBLT',
 'MH_PHQ_S',
 'BS1_1',
 'BS2_1',
 'BS3_1',
 'BS3_2',
 'BS3_3',
 'BS6_2',
 'BS6_2_1',
 'BS6_2_2',
 'BS6_3',
 'BS6_4',
 'BS6_4_1',
 'BS6_4_2',
 'BS5_4',
 'BS5',
 'BS5_1',
 'BS5_21',
 'BS5_28',
 'BS5_26',
 'BS5_33',
 'BS5_34',
 'BS5_32',
 'BS5_29',
 'BS5_30',
 'BS5_31',
 'BS8_2',
 'BS9_2',
 'BS13',
 'BS12_31',
 'BS12_32',
 'BS12_33',
 'BS12_34',
 'BS12_35',
 'BS12_36',
 'BS12_41',
 'BS12_42',
 'BS12_43',
 'BS12_44',
 'BS12_46',
 'BS10_1',
 'BS2',
 'BS10_2',
 'BS10_3',
 'BE3_71',
 'BE3_72',
 'BE3_73',
 'BE3_74',
 'BE3_81',
 'BE3_82',
 'BE3_83',
 'BE3_84',
 'BE3_91',
 'BE3_92',
 'BE3_93',
 'BE3_94',
 'BE3_75',
 'BE3_76',
 'BE3_77',
 'BE3_78',
 'BE3_85',
 'BE3_86',
 'BE3_87',
 'BE3_88',
 'BE9',
 'LW_MS',
 'LW_PR',
 'LW_PR_1',
 'LW_MT',
 'LW_MT_A1',
 'LW_MT_A2',
 'BM2_5',
 'MO4_4',
 'MO4_9',
 'MO4_7',
 'MO4_17',
 'MO4_11',
 'MO4_18',
 'MO4_15',
 'T_EX',
 'T_Q_VN',
 'N_INTK',
 'N_EN',
 'N_WATER',
 'N_PROT',
 'N_FAT',
 'N_SFA',
 'N_MUFA',
 'N_PUFA',
 'N_N3',
 'N_N6',
 'N_CHOL',
 'N_CHO',
 'N_TDF',
 'N_SUGAR',
 'N_CA',
 'N_PHOS',
 'N_FE',
 'N_NA',
 'N_K',
 'N_VA_RAE',
 'N_CAROT',
 'N_RETIN',
 'N_B1',
 'N_B2',
 'N_NIAC',
 'N_FOLATE',
 'N_VITC',
 'DN1_DG',
 'DN1_AG',
 'DN1_PR',
 'DN1_PT',
 'BS12_1',
 'BS12_2',
 'BS12_37',
 'BS12_47',
 'T_NQ_OCP',
 'HE_DM',
 'TOTAL_SLP_WK',
 'TOTAL_SLP_WD',
 'HE_UCREA']

In [107]:
index_list = []
for i in range(len(same_code_2)):
    if same_code_2.loc[i][0] in col_up:
        index_list.append(i)
index_list

[1,
 33,
 34,
 40,
 43,
 45,
 73,
 76,
 77,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 148,
 149,
 150,
 151,
 152,
 156,
 158,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 212,
 213,
 214,
 215,
 216,
 217,
 267,
 271,
 279,
 281,
 282,
 288,
 289,
 291,
 293,
 294,
 320,
 329,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 407,
 408,
 409,
 410,
 411,
 412,
 415,
 440,
 441,
 447,
 448,
 463,
 464,
 465,
 466,
 467,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 529,
 530,
 531,
 532,
 533,
 535,
 536,
 537,
 540,
 541,
 542,
 551,
 554,
 555,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 659,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 743,
 744,
 745,
 746,
 747,
 748,
 751]

In [108]:
len(index_list)

317