### 데이터 정리 (역순 처리)
* 역순 필요여부 작업 : Excel 
* 역순 처리 : python

### 분석전 과정

1. 역순처리에 쓰일 파일 생성 (변수사전 이용)

In [ ]:
## 라이브러리
import pandas as pd

In [2]:
## 데이터 불러오기
df = pd.read_csv('cor2_output.csv',encoding='cp949',index_col=0) # index_col = 0 : 0번째 컬럼을 인덱스로 사용하여라 
col = pd.read_csv('C:/sas_view/data/new_columns.csv',encoding='cp949',index_col=0) # 변수사전 데이터
df

        dis       var    Cor         dis_설명                var_설명
258  DC1_PR    DK4_PT  0.500    위암 현재 유병 여부              간경변증 치료
362  DC1_PR  EC_STT_2  0.524    위암 현재 유병 여부  (취업자) 종사상지위_임금근로자 상세
360  DC1_PR    BM13_3  0.461    위암 현재 유병 여부         치아손상 사유: 교통사고
92   DC1_PR    DC1_PT  0.772    위암 현재 유병 여부              위암 치료 여부
70   DC1_PR    BE3_78 -0.577    위암 현재 유병 여부     여가_고강도 신체활동 시간(분)
..      ...       ...    ...            ...                   ...
59   DM4_PR    BE3_77 -0.420  골다공증 현재 유병 여부    여가_고강도 신체활동 시간(시간)
66   DM4_PR    BE3_78  0.821  골다공증 현재 유병 여부     여가_고강도 신체활동 시간(분)
193  DM4_PR  AC3_1_02 -0.436  골다공증 현재 유병 여부           손상2 발생시기-년도
188  DM4_PR    DC6_PT  0.471  골다공증 현재 유병 여부             폐암 치료 여부
101  DM4_PR    BE3_74 -0.479  골다공증 현재 유병 여부      일_고강도 신체활동 시간(분)

[400 rows x 5 columns]

In [3]:
# df(상관계수df) 중 var에 해당하는 변수리스트 생성 (중복X)
var_s = set(df.iloc[:,1])
var_s = list(var_s)

In [4]:
## col(데이터에 대한 사전)의 구성확인
col.head(2)

      변수명   변수설명7   변수설명8
0      ID  개인 아이디  개인 아이디
1  ID_FAM  가구 아이디  가구 아이디

In [6]:
## 변수명 안에서 var_s에 해당하는 데이터만 추출
var_d = col[col['변수명'].isin(var_s)]
var_d

         변수명               변수설명7               변수설명8
20   KSTRATA             분산추정 층              분산추정 층
35    DI1_PT              고혈압 치료              고혈압 치료
36     DI1_2            혈압조절제 복용            혈압조절제 복용
38     DI2_2          이상지질혈증 약복용          이상지질혈증 약복용
40     DI3_2             뇌졸중 후유증             뇌졸중 후유증
..       ...                 ...                 ...
594   DN1_PR       신부전 현재 유병 여부   콩팥병(신장질환) 현재 유병 여부
595   DN1_PT             신부전 치료         콩팥병(신장질환) 치료
597   BS12_2    (성인) 전자담배 현재사용여부     액상형 전자담배 현재사용여부
598  BS12_37  (성인) 평생사용담배종류: 찐담배     궐련형 전자담배 평생사용여부
599  BS12_47  (성인) 현재사용담배종류: 찐담배     궐련형 전자담배 현재사용여부

[183 rows x 3 columns]

In [29]:
## 데이터 정리 중 역순처리를 위한 작업을 위해 csv파일로 내보내기
var_d.to_csv('var_d.csv',encoding='cp949')

2. 데이터 확인 작업 (var_c.csv / real_data1.csv)
* var_c.csv (상관분석을 통해 상관계수가 0.4이상인 변수들만 존재)


    * 제거여부
        * 0 : 질병에 영향을 미칠 가능성이 있다고 판단되는 변수들
        * 1 : 상관계수는 0.4 이상이지만 영향을 주지 않을 것 같다고 판단되는 변수들
    #
    * 변경여부
        * 0 : 설문지 응답문항이 큰 수일수록 긍정일 경우 (ex. 0 : 없음 / 1 : 긍정)
        * 1 : 부정이 더 큰 수에 해당하는 경우 (ex. 0 : 매우 그렇다 ~ 5 : 매우 그렇지 않다)

In [7]:
## 제거여부와 변경여부가 추가된 변수사전 csv 불러오기
var_df = pd.read_csv('var_c.csv',encoding='cp949')
var_df

         변수명               변수설명7  제거여부  변경여부                    변경사항  변경len
0    KSTRATA             분산추정 층      1   NaN                     NaN    NaN
1     DI1_PT              고혈압 치료     0   0.0                     NaN    NaN
2      DI1_2            혈압조절제 복용     0   1.0  1->5\n2->4\n4->2\n5->1    5.0
3      DI2_2          이상지질혈증 약복용     0   1.0  1->5\n2->4\n4->2\n5->1    5.0
4      DI3_2             뇌졸중 후유증     0   1.0              1->3\n3->1    3.0
..       ...                 ...   ...   ...                     ...    ...
178   DN1_PR       신부전 현재 유병 여부      0   0.0                     NaN    NaN
179   DN1_PT             신부전 치료      0   0.0                     NaN    NaN
180   BS12_2    (성인) 전자담배 현재사용여부     0   1.0          1 -> 2\n2 -> 1    2.0
181  BS12_37  (성인) 평생사용담배종류: 찐담배     0   0.0                     NaN    NaN
182  BS12_47  (성인) 현재사용담배종류: 찐담배     0   0.0                     NaN    NaN

[183 rows x 6 columns]

In [8]:
### 찐 데이터
age_1 = pd.read_csv('C:/sas_view/data/real_data1.csv',index_col=0)
age_1

C:\Users\dkq50\AppData\Local\Temp\ipykernel_17648\4183036353.py:2: DtypeWarning: Columns (31,32,202,265,277,288,291,331,372,399,411,437,443,464,475,482,510,518) have mixed types. Specify dtype option on import or set low_memory=False.
  age_1 = pd.read_csv('C:/sas_view/data/real_data1.csv',index_col=0)

,ID,ID_FAM,REGION,TOWN_T,APT_T,PSU,SEX,AGE,INCM,HO_INCM,...,DN1_PT,BS12_1,BS12_2,BS12_37,BS12_47,T_NQ_OCP,HE_DM,TOTAL_SLP_WK,TOTAL_SLP_WD,HE_UCREA
0,b'A651228902',b'A6512289',1.0,1.0,2.0,b'A651',2.0,78.0,3.0,1.0,...,NaN,2.0,NaN,NaN,NaN,2.0,2.0,480.0,480.0,128.4
1,b'A651417601',b'A6514176',1.0,1.0,2.0,b'A651',1.0,80.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.0,2.0,390.0,420.0,34.8
2,b'A652228901',b'A6522289',1.0,1.0,2.0,b'A652',1.0,66.0,3.0,3.0,...,NaN,2.0,NaN,NaN,NaN,2.0,3.0,390.0,390.0,269.8
3,b'A653184701',b'A6531847',1.0,1.0,1.0,b'A653',2.0,75.0,2.0,1.0,...,NaN,2.0,NaN,NaN,NaN,1.0,2.0,360.0,360.0,136.0
4,b'A653235705',b'A6532357',1.0,1.0,1.0,b'A653',2.0,79.0,4.0,3.0,...,NaN,2.0,NaN,NaN,NaN,2.0,3.0,240.0,240.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8398,b'R804176202',b'R8041762',8.0,1.0,2.0,b'R804',1.0,66.0,2.0,2.0,...,NaN,2.0,NaN,2.0,NaN,2.0,2.0,480.0,480.0,151.2
8399,b'R804205101',b'R8042051',8.0,1.0,2.0,b'R804',1.0,75.0,4.0,2.0,...,NaN,2.0,NaN,2.0,NaN,2.0,3.0,300.0,300.0,95.5
8400,b'R804205102',b'R8042051',8.0,1.0,2.0,b'R804',2.0,65.0,3.0,2.0,...,NaN,2.0,NaN,2.0,NaN,2.0,2.0,420.0,600.0,35.2
8401,b'R804344501',b'R8043445',8.0,1.0,2.0,b'R804',2.0,65.0,2.0,2.0,...,NaN,2.0,NaN,2.0,NaN,2.0,3.0,480.0,480.0,53.0
8402,b'R804371701',b'R8043717',8.0,1.0,2.0,b'R804',1.0,65.0,2.0,2.0,...,NaN,2.0,NaN,2.0,NaN,1.0,2.0,420.0,420.0,79.7

In [9]:
## 역순처리가 필요한 변수 추출
var_df[var_df.loc[:,'변경여부'] == 1]

,변수명,변수설명7,제거여부,변경여부,변경사항,변경len
2,DI1_2,혈압조절제 복용,0,1.0,1->5\n2->4\n4->2\n5->1,5.0
3,DI2_2,이상지질혈증 약복용,0,1.0,1->5\n2->4\n4->2\n5->1,5.0
4,DI3_2,뇌졸중 후유증,0,1.0,1->3\n3->1,3.0
13,DJ4_3,천식 약복용,0,1.0,1 -> 3\n3 -> 1,3.0
14,DE1_3,당뇨병혈당관리치료여부,0,1.0,1 -> 2\n2 -> 1,2.0
56,BP5,2주이상 연속 우울감 여부,0,1.0,1->2\n2->1,2.0
57,BP6_10,1년간 자살 생각 여부,0,1.0,1->2\n2->1,2.0
151,BS5_4,(성인) 니코틴의존,0,1.0,1 -> 4\n2 -> 3 \n3 -> 2 \n4 -> 1,4.0
154,BS5_21,(성인) 금연방법: 의지로,0,1.0,0 -> 1\n1 -> 0,1.0
155,BS5_34,(성인) 금연방법: 병의원을 통해 니코틴 대체용품 구입,0,1.0,0 -> 1\n1 -> 0,1.0
156,BS8_2,(성인) 직장실내 간접흡연 노출 여부,0,1.0,1 -> 2\n2 -> 1,2.0
158,BS12_46,(성인) 현재사용담배종류: 피운 적 없음,0,1.0,0 -> 1\n1 -> 0,1.0
165,BE3_91,장소이동 신체활동 여부,0,1.0,1 -> 2\n2 -> 1,2.0
176,T_Q_VN,이명 여부,0,1.0,1 -> 2\n2 -> 1,2.0
180,BS12_2,(성인) 전자담배 현재사용여부,0,1.0,1 -> 2\n2 -> 1,2.0

In [10]:
## 해당 변수의 데이터들 추출 (test로 DI1_2 변수 확인)
n = 2
age_1.loc[:,var_df.iloc[n][0]]

0       1.0
1       1.0
2       NaN
3       NaN
4       1.0
       ...
8398    1.0
8399    5.0
8400    NaN
8401    NaN
8402    NaN
Name: DI1_2, Length: 8403, dtype: float64

### 변경이 필요한 변수 변경 작업 실시

In [102]:
for n in list(var_df[var_df.loc[:,'변경여부'] == 1].index): ## 변경여부가 1인 변수들 (역순처리 필요한 변수)
    # print(var_df.iloc[n][0]) ## 변수 확인을 위함
    m = int(var_df.iloc[n][5]) # 변경len : 응답문항에서 가장 큰 수를 뜻함 ex) 1 2 3 4 5 -> 5 / 0 1 -> 1
    
    ## 역순 처리
    for i in range(0,len(age_1)):
        if  m > 1:    
            for j in range(0,m): 
                if age_1.loc[:,var_df.iloc[n][0]][i] == m-j: ## ex) 5 -> 1 / 4 -> 2 / 3 -> 3 / 2 -> 4 / 1 -> 5
                    #print('변경전: ', test[i])
                    age_1.loc[:,var_df.iloc[n][0]][i] = j+1
                    #print('변경후:',test[i])
        elif m == 1:
            #print('변경전: ', test[i])
            age_1.loc[:,var_df.iloc[n][0]][i] = abs(age_1.loc[:,var_df.iloc[n][0]][i]-1) ## 1 -> 0 / 0 -> 1 
            #print('변경후:',age_1.loc[:,var_df.iloc[n][0]][i])

DI1_2

C:\Users\dkq50\AppData\Local\Temp\ipykernel_22668\3441485827.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  age_1.loc[:,var_df.iloc[n][0]][i] = j+1

DI2_2
DI3_2
DJ4_3
DE1_3
BP5
BP6_10
BS5_4
BS5_21

C:\Users\dkq50\AppData\Local\Temp\ipykernel_22668\3441485827.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  age_1.loc[:,var_df.iloc[n][0]][i] = abs(age_1.loc[:,var_df.iloc[n][0]][i]-1)

BS5_34
BS8_2
BS12_46
BE3_91
T_Q_VN
BS12_2

In [103]:
## 역순처리된 데이터
age_1.to_csv('test_df.csv')